### ISSUE TITLE
[ANDROID] Events never stop firing.

### ISSUE THREAD

**Issue by jffs** [j3k0/cordova-plugin-purchase#1001]
Hi, thanks for this plugin. It works properly (at least on Android). I have a question. when i execute the following code, the events never stop fireing. Is this the normal behave?  

```
this.iap2.when(productId).updated((product) => {
      if (product.owned) {
        console.log('ES UN SUSCRIPTOR');
        this.premium = true;
        product.finish();

      }
    });
    this.iap2.when(productId).owned((product: IAPProduct) => {
      // product.finish();
    });
```

**Comment by Taylorsuk** [comment]
@jffs I am having this issue too. I think that the method `.owned` somehow then triggers the updated and then you end up in a loop. For this reason I have chosen to use the `.once` method and opting to be very explicit about the functionality of the app. 

So far, I have not been able to find a nice way of unregistering the `.when` method once registered as the `product.finish()` doesn't seem to work for me.

**Comment by Taylorsuk** [comment]
After a little more research I see that you can use the `.off` method. 

HOWEVER, as written https://github.com/j3k0/cordova-plugin-purchase/issues/813 the listeners should be running in the app all the time, so we should maybe figure out how to stop the loop, yet not stop listening.

**Comment by jffs** [comment]
Hi @Taylorsuk thanks for sharing your experience. Could you post some code to explain the `.off` and .`once `method? where did you use it? I can't stop the loop and that has an impact in my app performance.

**Comment by Taylorsuk** [comment]
@jffs for your code I would look to do

```
this.iap2.when(productId).updated((product) => {
  if (product.owned) {
    console.log('ES UN SUSCRIPTOR');
    this.premium = true;
    product.finish();
  }
});
```

```
this.iap2.once(productId).owned((product: IAPProduct) => {
    // product.finish();
});
```

Ensuring that `.owned` on my app was only called once prevent this loop from firing none stop. **however**, you must be aware of the lifecycle of this plugin in order to ensure that you are listening for the correct calls. For me, I manage the subscription via the users account (for access to paid features) so the continued monitoring of the state of the subscription is managed elsewhere.

**Comment by jffs** [comment]
Thanks, could I contact to you via email to clarify some concepts about this plugin and the whole cycle? to avoid making noise in this thread

**Comment by Taylorsuk** [comment]
I'm certainly not the voice of authority on this plugin, I only shared my experiance to see if it could help. I believe the author has a notice on the repo front page offering assistance as a service, I would probably reach out to him rather than me as I've only just been able to figure out a working implementation myself.

**Comment by j3k0** [comment]
Hey, `update` is called when you perform a change to the product. If you call `finish()` from the `update()` function you can create this call loop.

`finish()` should be called from the `verified` or `approved` event handlers (depending if you use server-side receipt validation.

**Comment by j3k0** [comment]
Note:

```js
if (product.owned) {
        console.log('ES UN SUSCRIPTOR');
        this.premium = true;
        product.finish();
      }
```

Doesn't really make sense. The product is set to `owned` when you call `finish`.

Basically your product will ping-pong between finished and owned.

See https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#life-cycle

**Comment by pencilcheck** [comment]
The documentation isn't very clear, I thought those events are called when user make a change but turns out it is called on every method call from product as well as from the server as well.

So "updated" isn't doing what I thought it is doing, so gotten infinite loop right away since I called "product.finished()" inside "approved".
