### ISSUE TITLE
[IOS] product is owned although no purchase happaned

### ISSUE THREAD

**Issue by HarelM** [j3k0/cordova-plugin-purchase#1009]
### system info

Please report your OS, OS version, Compiling System and Version, used Plugin Version and any helpful information that can help us to resolve the problem.

In example:
```
MacOS with latest, not sure what's the version.
Cordova 9.0.0 
Device: iPhone iOS 13.1
Plugin Version: 10.0.1
```

### Expected behavior
When registering an auto renewal subscription product owned flag should be false

### Observed behavior
When registering an auto renewal subscription product owned flag is on for iOS

### Steps to reproduce
The following code work well for android but report owned on iOS:
https://github.com/IsraelHikingMap/Site/blob/b31bfc18824fd190107bb530b9cc79c7fcc41180/IsraelHiking.Web/sources/application/services/purchase.service.ts#L30

I changed the code from `product` to the product id `offline_map`, I hope this is the right solution, otherwise I'll be loosing some money on free subscriptions...

**Comment by HarelM** [comment]
Also it seems that the events in the fovea billing is different for ios and android:

ios: Receipt validated il.org.osm.israelhiking on ios. <-- is this a security issue that this product id gets validated although it's not valid?
android: Receipt validated offline_map on android. <-- this one is the correct product id.

**Comment by HarelM** [comment]
Seem like the validation call is made although it wasn't configured to do so too for the app name (not the product - il.org.osm.israelhiking in my case).
Can anyone please comment on this? Please?
@Dexus @j3k0 
Might be related to #1012 as well, I don't know...

**Comment by j3k0** [comment]
The `owned` flag is cached for cases where the device is offline.

`owned` can't be set if your code doesn't call `finish()` for a given product. Maybe you get `owned=true` for the `il.org.osm.israelhiking` product?

`il.org.osm.israelhiking` is your bundle ID, the plugin validates the `appStoreReceipt` at startup using this "virtual" product ID. No security issue. This has a number of advantages, so to keep things simple we just validate the app receipt in all cases. The list includes: retrieve data about the app download like date and version of first app install and current install, ensure we have an up-to-date receipt (refreshed server-side), check if the user is eligible to discount offers and introductory offers, ...

We're trying to migrate receipt validation from the legacy per transaction receipt to app receipt in a backward compatible way. That's why we're validating both in different context.

**Comment by HarelM** [comment]
Thanks for getting back to me! :-)
I'm guessing the documentation needs to be updated a bit if I'm getting an `owned` for `il.org.osm.israelhiking`.
See documentation here:
https://billing-dashboard.fovea.cc/setup/cordova/
I was under the impression I can listed to updates on "products", I did not know there's a product I did not create.
In any case, I'm guessing this issue can be closed. Listing to a specific product ID solves this issue.
Thanks for the detailed information.

As as side note, I'm using the fovea billing server events page to monitor which clients that have paid used the app, and the "virtual" product kinds of clutter this page. Not sure there's much to do in that case, but worth noting.
Let me know if you want me to move this request to the fovea billing repo issues...
