### ISSUE TITLE
IOS: store return object with product list and puchased product

### ISSUE THREAD

**Issue by fitmax-project** [j3k0/cordova-plugin-purchase#1030]
system info
Ionic:

Ionic CLI : 5.4.11
Ionic Framework : @ionic/angular 4.11.8
@angular/core: 8.2.14"
@ionic/angular: "^5.0.0"

Cordova:
  "cordova-android": "8.1.0",
    "cordova-ios": "5.1.1",

plugin:
"cc.fovea.cordova.purchase": "^10.1.1",
### Expected behavior
return only the product list, not puchased one

### Observed behavior
i have 4 product in appstoreconnect and for somereasion after register i get a list of 5 products
4 of product
1 purchased item with the recipet and everything....
### Steps to reproduce
the code:
```
  private storeProducts: IAPProduct[] = [];
  public set _storeProducts(v: IAPProduct[]) {
    this.storeProducts = v;
  }

  public get _storeProducts(): IAPProduct[] {
    return this.storeProducts;
  }


public initStore() {
      this.Service.getPlans().subscribe((plans) => {
        const products = plans.map((product) => {
          return {
            id: product.productId,
            type: this.store.PAID_SUBSCRIPTION,
          };
        });
        this.prepareStore(products);
      });
  }

  prepareStore(products: IAPProductOptions[]) {
    this.store.validator =
      "https://validator.fovea.cc/v1/validate?xxxxxxxxxxxx";
    this.store.register(products);

    this.store.refresh();

    this.store.error((err) => {
      console.error("Store Error " + JSON.stringify(err));
    });

    this._storeProducts = this.store.products;
  }
```

**Comment by j3k0** [comment]
The 5th product is probably your application bundle. This question has been answered multiple times.

The plugin validates the appStoreReceipt at startup using this "virtual" product ID, because Apple attached data to the receipt for your download. This has a number of advantages, so to keep things simple we just validate the app receipt in all cases. The list includes: retrieve data about the app download like date and version of first app install and current install, ensure we have an up-to-date receipt (refreshed server-side), check if the user is eligible to discount offers and introductory offers, ...

**Comment by fitmax-project** [comment]
yea... but i dont want it to show....it on my product-to-buy list...

**Comment by j3k0** [comment]
You can filter it out. `product.type` will be `application`.
