### ISSUE TITLE
store.update() vs store.refresh()

### ISSUE THREAD

**Issue by remisture** [j3k0/cordova-plugin-purchase#1034]
I'm upgrading from version 8 to 10, and see you have added `store.update()` since last time I worked with this plugin. Is `store.update()` a drop-in replacement of `store.refresh()`? If not, when to use `update()`, and when to use `refresh()`? I think the documentation lacks a bit here :)

Thanks for a great plugin.

**Comment by j3k0** [comment]
Sorry the documentation is lacking.

Using `store.update()` is optional. It's a "soft refresh". I advise you call when entering your "Store" screen to make sure you have the most up-to-date prices (in case this changed since the app started). Use `store.refresh()` did not change.

**Comment by j3k0** [comment]
Note, doc is here: https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#-storeupdate

Let me know if this is lacking, or if you missed this doc, where did you get info about this method (where I could add a little more, like a link to the above).

**Comment by canadaka** [comment]
Can one JUST call `store.update()` without ever calling `store.refresh()`? To just get a subscription products pricing info?

**Comment by j3k0** [comment]
You should **always** call `store.refresh()` at app startup. Purchases can be made outside the app, this is when the plugin will trigger events for those purchases. It'll also ping the receipt validator for cancellations, renewal, etc.

**Comment by canadaka** [comment]
We are handling cancellations and renewals on the server with server-to-server messaging. Each time our app starts we make our own API call to our servers to see if the users subscription is valid. Our server is always the source of truth.

I had recently changed our code to only call store.refresh when the payment page is entered in our app, rather than on every app startup. Your saying I should be calling it on app startup and always listing for all those events?

We are nervous about calling store.refresh() and having it prompt for the users apple account password.

**Comment by svzi** [comment]
Hi @canadaka, how did you proceed? We're currently facing the same issue and a lot of beta testers start to complain about the fact that they need to enter their Apple Password on every app launch. That does not seem to be a user friendly solution. I wouldn't use an app where I would need to authenticate to the app store on every single launch...

Our backend is our source of truth as well, but not every user has his own account. For those who have, we store the receipt data in their account and validate it on our server from time to time. For those with account I skip the `store.refresh()` on app start and do it only when the user enters the purchase page. But for all the other users, without own account, the issue seems to be really annoying...

Any feedback would be really much appreciated, as I'm looking for better solutions.

**Comment by j3k0** [comment]
The **first** call to `store.refresh()` will never ask for the password in production.

In iOS, there are 2 different ways to retrieve the `appStoreReceipt`:

1. Get the path to the locally cached receipt, load it from file system.
2. Initiate an appStoreReceipt refresh request, wait for user to enter credentials and receive the data.

In case the app was downloaded through the AppStore (and there are no other options in production on iOS) there always will be an `appStoreReceipt` cached and available to the app: a download through the AppStore generates a receipt for everyone.

In case the app was downloaded through TestFlight or XCode, there might not be a receipt generated. If the `appStoreReceipt` is required for receipt validation (with a call to `verify()`), the plugin will resort to initiate an receipt refresh request (which asks for a password, and will generate a receipt).

At startup, in production, every time I debugged someone's app that complained the password was required at startup, it was because some way or another they were calling `refresh()` multiple times.

Subsequent calls to `refresh()` on iOS will always trigger a full refresh of the receipt (because it IS useful, when someone switch AppStore account, he wants to go back to the app, hit "Restore Purchases", and gets the updated purchases).

**Comment by j3k0** [comment]
...If you don't want your beta testers to be annoyed by this, I believe you can delay the call to `product.verify()`, with some custom strategy.

An example complex implementation.

```js
store.when().approved(product => {
  MySessionManager.ready(userSession => {
    if (userSession.hasServerSideReceipt)
      return product.finish(); // no need to re-validate, we already have a receipt server-side
    if (userSession.isAnonymous)
      return product.finish(); // anonymous users cannot make purchases

    if (product.type === store.APPLICATION) {
      // this is the plugin asking if it should validate the application receipt, we don't know it server side for this user.
      needReceiptValidation = true;
    }
    else {
      // there's a regular purchase on the device, we should verify it.
      product.verify();
    }
  });
});
```

Somewhere in your UI code, if `needReceiptValidation` is true you can show an info message (or bullet) telling the user that you didn't check yet the status of their purchase ("please hit Check Purchases" > triggers a call to `store.get(store.APPLICATION).verify()` > apple asks for credentials > server gets the receipt`

Beware that you should still force a receipt validation if the user refreshes the receipt (it might come with a different one).

```js
let forceValidation = false;

function restorePurchases() {
  forceValidation = true;
  store.refresh();
}

store.when().approved(product => {
  if (forceValidation) return product.verify();
  // then as above ...
});
```

This is all very complicated and only really useful for Beta testers.
