### ISSUE TITLE
register product with type 'application'

### ISSUE THREAD

**Issue by hazmouneZaineb** [j3k0/cordova-plugin-purchase#1044]
### system info

```
Mac 10.15.4
Cordova 9 
Device: iPad iOS 13.4.1
Plugin Version: 10.1.1
Using Ionic with package: "@ionic-native/in-app-purchase-2": "5.25.0"
```

### Expected behavior
```store.register```  must register only the requested products
### Observed behavior
after registering my products and viewing ```store.products```, I see a product with an alias 'application' (I register four products but the store.products returns five) this product is in an approved state and has a transaction, when I receive validation on my server the receipt contains the product which must be renewed automatically but the auto renew failed and the transaction expired).
After expiration, this product is still in an approved state, and I can't purchase any more, All this products are in valid except this one 
``` 
{
    additionalData: null
    alias: “application”
    canPurchase: false
    countryCode: null
    currency: null
    deferred: undefined
    description: null
    discounts: [] (0)
    downloaded: false
    downloading: false
    expired: true
    group: “”
    id: “com.test.mytest”
    ineligibleForIntroPrice: null
    introPrice: null
    introPriceMicros: null
    introPriceNumberOfPeriods: null
    introPricePaymentMode: null
    introPricePeriod: null
    introPricePeriodUnit: null
    introPriceSubscriptionPeriod: null
    loaded: true
    owned: false
    price: null
    priceMicros: null
    state: “approved”
    title: null
    transaction: {type: “ios-appstore”, appStoreReceipt:“MIIbTwYJKoZIhvcNAQcCoIIbQDCCGzwCAQExCzAJBgUrDgMCGg…  nZOGURNomxfbzMoX7KmXLPvH2iCIpoDEekQQMNtLc=“, signature: undefined}
    type: “application”
    valid: true
    version: “2.6.71"
}
 ```
### Steps to reproduce

1. purchase product type PAID_SUBSCRIPTION

1. test code  ```console.log(store.products) ```

**Comment by DaLooK** [comment]
I've had the same "problem" with an "application" type product.
Just made my validation server return an "ok" with this particular product and everything worked fine again.

**Comment by hazmouneZaineb** [comment]
thanks @DaLooK, the validation return ok and the product will be finished ?

**Comment by hazmouneZaineb** [comment]
@DaLooK I tested your solution, it works perfectly now, thank you very much, but what is the meaning of this production? why it is automatically registered after the first purchase?

**Comment by DaLooK** [comment]
I'm not really sure what does this "application" type product means. I didn't found anything in the documentation.
Had problems with it for at least a month in production. I'm really glad I could help you resolve your problem.

**Comment by Dexus** [comment]
The "application" type is a automatic generated "purchase" from the vendor (apple store/google playstore). If you have a server side validation you and you did not sale you application and give it for free, you can ignore this and response "ok" for it without future validation.

**Comment by vo-va** [comment]
@Dexus I have question about "application" type transactions. My understanding may be completely wrong, please correct me.

From what I see they are valid. And in my case I stumble on them after these steps (Appstore)

- purchase subscription with server side validation
- validation didn't passed (intentionally)
- now after application starts, it sending to validation server requests with "application" type transaction

If I will validate receipt then Apple server confirm that receipt is valid and return to me a list of renewed subscription (during testing/sandbox subscriptions has small life, so there are bunch of them)

Since they are valid but server side validation didn't finished, I need to restore them. In particular I need to link expiration date from last transaction/subscription to user in my DB. But because request (you can see it in the first message of this issue/question) does not have information in `additionalData`, I can't do this.

I am gusseting that transaction "application" type generated after `store.refresh()`. And it is necessary to restore purchased subscriptions.

How I can attach `additionalData` to transaction with `application` type? I need to put into it user id to link approved receipts to user.

If this is wrong approach, then how I can restore old purchases? In application code I am doing `window.store.refresh();`
