### ISSUE TITLE
> [iOS] I wasn't able to test a failed purchase on iOS, but it would be nice to get a confirmation on iOS's behavior when a decline card is used. (Or how to test a failed purchase with sandbox)

### ISSUE THREAD

**Issue by vinayNdz** [j3k0/cordova-plugin-purchase#1063]
> [iOS] I wasn't able to test a failed purchase on iOS, but it would be nice to get a confirmation on iOS's behavior when a decline card is used. (Or how to test a failed purchase with sandbox)

@Lindsay-Needs-Sleep Hi, I need some help regarding the in-app purchase in iOS. This is my code, here I want to implement a non-renewable subscription. And when the approved event is triggered I'm passing the appStorereceipt to my server where it calls the verifyReceipt api to apple server from backend and returns the receipt in a human readable form to backend and on success I'm navigating it to a new page. This is what I'm doing here. My doubt are 

1. Is that approved event triggers only when a successful payment is done ?
2. How do we know if the payment got declined by the apple server ? Is their any response from apple server? 
3. If the purchase is unsuccessful does the approved event trigger?

If the payment got declined by the bank or from the apple server I need to do some other functionality. Anticipating your response. Any information would be much helpful. Thanks

`
constructor() {
this.setup();
}
setup() {
      this.store.register({
      id: "lite30",
      type: this.store.NON_RENEWING_SUBSCRIPTION,
      alias: "lite30",
    });

    this.store.register({
      id: "premium365",
      type: this.store.NON_RENEWING_SUBSCRIPTION,
      alias: "premium365",
    });

    // restore purchase
    this.store.refresh();
  }

  registerHandlersForPurchase(productId) {
    let self = this.store;
    let planid;
    if (productId == "lite30") planid = 2;
    else planid = 3;

    this.store.when(productId).updated(function (product) {
      console.log("enteredqwe");
      if (
        product.loaded &&
        product.valid &&
        product.state === self.APPROVED &&
        product.transaction != null
      ) {
        product.finish();
      }
    });

    this.store.when(productId).approved((product: IAPProduct) => {
      product.verify();
      if (
        this.email != "" &&
        this.email != undefined &&
        this.userid != "" &&
        this.userid != undefined
      ) {
        this.commonService
          .inAppPayment(
            this.userid,
            planid,
            product.transaction.appStoreReceipt
          )
          .subscribe(
            (res) => {
              if (res.result_status) {
                this.loader.hideLoader();
                product.finish();
                this.navCtrl.setRoot(MenuPage);
              } else {
              }
            },
            (error) => {
              console.log(error);
            }
          );
      }
    });
  }

  /* PAYMENT PROCESS */
  planSelect(plan) {
    console.log("enteredplanselect", 1);
    this.isEnabled = false;
    setTimeout(() => {
      this.isEnabled = true;
    }, 15000);
    this.registerHandlersForPurchase(plan);
    try {
      let product = this.store.get(plan);
      this.store
        .order(plan)
        .then((p) => {
          this.store.when(plan).initiated((p: IAPProduct) => {
            this.registerHandlersForPurchase(plan);
          });
        })
        .catch((e) => {
          console.log(e);
        });
    } catch (err) {
      console.log("Error Ordering " + JSON.stringify(err));
    }
  }`

_Originally posted by @vinayNdz in https://github.com/j3k0/cordova-plugin-purchase/issues/1047#issuecomment-653496572_

**Comment by Lindsay-Needs-Sleep** [comment]
Hi @vinayNdz 
I am in no way an expert, but I'll try to answer your questions.

** First, I have only worked with **auto-renewing** subscriptions, so I'm not sure if everything will be exactly the same for the **non-renewable** subscriptions.

** [Here is spread sheet I have been working on that shows the flow of store events](https://docs.google.com/spreadsheets/d/1LP0WPx-ftPk30HsFnYSZFrimXoLiTvdyNLH-rHNZars/edit?usp=sharing).  This *might* help with some understanding.  I created this by putting console logs everywhere.  Most of my answers below are based on information from this spreadsheet.

First, you should probably change this:
```js
this.store.when(productId).approved((product: IAPProduct) => {
  product.verify();
  if (
    this.email != "" &&
    this.email != undefined &&
    this.userid != "" &&
    this.userid != undefined
  ) {
    this.commonService
      .inAppPayment(
        this.userid,
        planid,
        product.transaction.appStoreReceipt
      )
      .subscribe(
        (res) => {
          if (res.result_status) {
            this.loader.hideLoader();
            product.finish();
            this.navCtrl.setRoot(MenuPage);
          } else {
          }
        },
        (error) => {
          console.log(error);
        }
      );
  }
});
```

To something like this (to properly use the validator):
```js
// Queries the server (which then asks google/apple/etc) to ensure it is a valid subscription
// Docs here: https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#validator
this.store.validator = function (product, callback) {
    if (
        this.email != "" &&
        this.email != undefined &&
        this.userid != "" &&
        this.userid != undefined
      ) {
        this.commonService
          .inAppPayment(
            this.userid,
            planid,
            product.transaction.appStoreReceipt
          )
          .subscribe(
            (res) => {
              if (res.result_status) {
                this.loader.hideLoader();
                product.finish();
                this.navCtrl.setRoot(MenuPage);
                // Since you are navigating away, this won't get called, but this is the "proper" way
                callback(true);
              } else {
                // If your validator has a problem, or if the subscription is invalid
                // Return false and an error code
                // error codes: https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#validation-error-codes
                callback(false, {code: store.PURCHASE_EXPIRED});
              }
            },
            (error) => {
              console.log(error);
              // If your validator has a problem, or if the subscription is invalid
                // Return false and an error code
                // error codes: https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#validation-error-codes
                callback(false, {code: store.CONNECTION_FAILED});
            }
          );
      }
};
this.store.when(productId).approved((product: IAPProduct) => {
  product.verify();
});
```
The `store.validator` will called by `product.verify()`.  
And then *technically* depending on whether you do `callback(true)` or `callback(false, ...)` the next event `product.verified` will be called.  (NOTE: I do seem to have noticed the `callback(false, ...)` not working correctly, but I did not test this much, and gave up quickly.)

## QUESTIONS

> Is that approved event triggers only when a successful payment is done ?

According to my spreadsheet I have observed the `approved` event fires:  
- After a successful purchase
- If the user currently owns a valid subscription, if you reload the page (eg. register products and store.refresh())
- If the user owns an **expired** subscription, if you reload the page (eg. register products and store.refresh())

So I guess the `approved` event will fire anytime the plugin detects that the user owns something.  It will be up to your validator to decide if the user currently owns a valid subscription.

> How do we know if the payment got declined by the apple server ? Is their any response from apple server?

I don't know this for sure.  For **Google**, the `approved` event is **not** called (and we never get to the validator at all).  Hopefully it is the same for iOS.

> If the purchase is unsuccessful does the approved event trigger?

Pretty much the same answer as above.  I don't really know. :(  
If the purchase is unsuccessful because the user **cancels** the purchase, the `approved` event is **not** triggered.  (You can see [my spreadsheet](https://docs.google.com/spreadsheets/d/1LP0WPx-ftPk30HsFnYSZFrimXoLiTvdyNLH-rHNZars/edit#gid=769086893) for more details on what **does** happen during certain situations.)

> If the payment got declined by the bank or from the apple server I need to do some other functionality. 

I guess, the easiest, and most reliable, might be to re-enable your purchase button on a failed validation.  (If you disabled the UI or anything).

**Technically** I believe the proper solution is to:
- For success: Your validator should call `callback(true);` and then on `product.owned` event you should do the redirect
- For failure: Your validator should call `callback(false, <some error>);`, and then on `store.error` event you should handle the error appropriately.  (eg. re-enable purchase UI, or re-attempt validation, or display an error to user, etc)

But according to my spreadsheet `callback(false, ...);` doesn't seem to work as it is supposed to.... (But I didn't spend too long trying this out.)


## OVERALL

In your validator, if you are checking if the subscription is valid (not expired), and then re-directing the user...  *I think* that should be fine.  (This is very similar to what we ended up doing.)

I also just stumbled across this [cordova-non-renewing-subscription](https://github.com/j3k0/cordova-non-renewing-subscription).  It might be good for your purposes.

**Comment by vinayNdz** [comment]
@Lindsay-Needs-Sleep I've copied the code you mentioned but now validator is not calling and all the functions inside it are not hitting

**Comment by Lindsay-Needs-Sleep** [comment]
That is strange.  I don’t know why it wouldn’t work for you.

But I guess you can just use it the way you had it before if that was working.  (sorry)

**Comment by vinayNdz** [comment]
@Lindsay-Needs-Sleep What if I hadn't added any payment cards in my iCloud account? Does it automatically redirects to App Store to add the card details ? Right now I've checked the sandbox method but using sandbox they didn't ask for cards right , you just've to put the password to complete a purchase. I also checked on a device without having the sandbox account but there when I click buy a pop up comes asking for Apple ID and password. When I enter those details the pop up closes and then nothing happens.

**Comment by Lindsay-Needs-Sleep** [comment]
Sorry, I have no idea. :(
I have only tested with the sandbox account.

I’m not sure what the expected behaviour is supposed to be for non-sandbox accounts.   

It does seem like it would make sense for Apple to immediately ask the user to enter their card info.  I don’t know if that is a bug on Apple’s part or not (or if it is a bug in this plugin).

**Comment by vinayNdz** [comment]
@Lindsay-Needs-Sleep okay thank you for the informations :) .

**Comment by Lindsay-Needs-Sleep** [comment]
I think this would still be useful to know (and document), if anyone figures it out in the future.
