### ISSUE TITLE
[ANDROID] Account Hold and Restore will become mandatory - is action required?

### ISSUE THREAD

**Issue by viking2917** [j3k0/cordova-plugin-purchase#1068]
### system info

Question is common to all Android versions and usage of this plugin.

### Expected behavior

I recently received an email from Google stating that Account Hold and Restore will be mandatory as of November 1. I could not find specific documentation for this plugin regarding these features. My quick reading of various documents suggests this will "just work", but it would be great to have official confirmation of that. 

Are any changes from the "normal" implementation path required? 
(for reference I use the Fovea receipt validator)

```
Starting on November 1, 2020, Account hold and Restore will both be mandatory.
Account  hold is a state the user enters after a renewal fails due to a payment  issue. During account hold, the user loses access to the subscription  while Google notifies the user and retries the payment method. Learn how to integrate Account hold.

The  Restore feature enables users to resume auto-renewals after they have  cancelled the subscription but before the subscription expires. Learn how to integrate Restore.
```

**Comment by coleburg** [comment]
IOS are also implementing Hold and Restore to their subscriptions, so also interested in this thread.

**Comment by HarelM** [comment]
I got the same mail from google. Let me know if you find out anything about it.
I saw that there was an update to the google billing library in version 10.2 but this version was not released to npm so I'm not sure what's the status of this...

**Comment by Dexus** [comment]
As far as I understand it, it only affects the server side with the validation.

I have to take a close look again, because from November on the V3 Client and/or Server will be mandatory as well.

**Comment by EvelinJK** [comment]
> IOS are also implementing Hold and Restore to their subscriptions, so also interested in this thread.

Do you have any links or further infos for that? I can't really find any info about an upcoming iOS hold/restore functionality.

**Comment by rafaellop** [comment]
Do you maybe have some idea how the server side flow should be like?

**Comment by moshi100** [comment]
Hi! anyone has an update? 
It clearly write in Play store console that any developer need to make some changes to in-app subscriptions:

> You must have account hold and restore implemented in your app by 1 November 2020.

Looks like "account hold" is not implemented in this plugin, or do I misunderstanding?
Thanks!

**Comment by Lpn01** [comment]
Hi. As far as I understood the documentation (I often find Google's docs hard to understand for whatever reason), it means the following.

For the hold part:
-> suppose a user is subscribed and then his/her subscription expires;
-> we find out the subscription is expired (either through the webhook calling our server or through us calling Fovea to check the status of the subscription);
-> the benefits for the user are removed;
-> later, Google manages to capture a new payment; at this step, either through the webhook or through calling Fovea, we should discover that the user has had his/her subscription reenabled ('isExpired' is false or however we check that) because the payment was captured; therefore, we enable his/her account, which was only on "hold" (we just removed their benefits, but nothing was forever gone and the subscription simply continues from now on with no other action required from the user). 

In other words, Fovea needs to be able to recognise that user might today have an expired subscription, and a couple of days later, the subscription is valid without the user even opening the app. We, the developers, need to be able to restore their benefits again, without the user opening the app. 

The question is, is Fovea actually able to recognise that users who had an expired subscription now have one that is not expired and valid? I believe Fovea needs to call the service account to find that out. 



For the restore part: 

As I understood, this concerns users who cancel their subscription at some point but enable it again before it expires. I never cancel their benefits until the subscription is expired so I am not too concerned about this. 


Maybe I've got that all wrong, but this was my understanding at least. I'm going to forward this to Fovea hoping they'll reply, their support through email has been amazing so far.

**Comment by nprather** [comment]
These two parts of the docs were helpful for me.  Given the massive amounts of app in the Google Play Store that use subscriptions, I gotta think they'll do some sort of automated test to look for apps that don't have these settings set in the Google Play Console.  I just ENABLED the Account Hold for my in app purchase sub, and then ENABLE the Pause feature.  
My fingers are crossed that this will fix the problem, although I may need to update my backend to trap for the Hold notification, etc.

To enable account hold, do the following:

Sign into the Google Play Console
Select your app.
In the left-hand menu, choose Store presence > In-app products.
Select the Subscriptions tab, and expand the Subscription settings section.
Check Activate account hold.

[https://developer.android.com/google/play/billing/subs#account-hold](url)

[https://developer.android.com/google/play/billing/subs#pause](url)

**Comment by arturios1916** [comment]
Is there someone with a clear explanation or instruction?

Our app uses GP subscriptions, but we listening changes directly from the Stores. 
Once subscription lost 'owned' and 'approved' flags - we block access to paid features.

Should we adjust something?

**Comment by j3k0** [comment]
The plugin supports "Account Hold".

On the client side, a subscription in "Account Hold" state will not be present when the app is started (so it won't be owned).

On the server / receipt validation side. The purchase will have an expiry date in the past and payment state set to pending. Fovea's receipt validation service will set `isBillingRetryPeriod` to true when the payment is pending.

 * `isBillingRetryPeriod && isExpired` = Account Hold
 * `isBillingRetryPeriod && !isExpired` = Grace Period

In those cases, it's advised to display a notification like this in the app "There is a problem with your subscription. Click here to go to the Google Play subscription settings to fix your payment method.", with a button to open the payment settings with `store.manageBilling()`.

**Comment by j3k0** [comment]
> The question is, is Fovea actually able to recognise that users who had an expired subscription now have one that is not expired and valid? I believe Fovea needs to call the service account to find that out.

Fovea implements this in 2 ways:

1. refresh recently expired subscriptions every hour, for 7 days, with the Developer API (active pulling).
2. real-time server notifications that trigger a refresh (passive pushing)

Option 2 prevents some lag in detection of reactivation, if the user uses the app outside the device. On device, no issue since receipt are validated every startup. We're updating the documentation for option 2 (since Google changed the developer console, we're redocumenting this process).

In any case, support is in place.

**Comment by viking2917** [comment]
Per the above explanation, closing this issue.
