### ISSUE TITLE
[UWP] product.title is empty

### ISSUE THREAD

**Issue by dominic-simplan** [j3k0/cordova-plugin-purchase#1070]
### system info

```
Cordova 9.0.0
Device: Windows 10
Plugin Version: 10.0.1
```

### Expected behavior
The product.title value should be filled with the addon/subscription name as defined in the Windows Store.

### Observed behavior
The product.title is empty
![grafik](https://user-images.githubusercontent.com/22240239/87349494-ac7db400-c556-11ea-9464-ed5956e8197b.png)

I believes this occurred after I've updated from plugin v8.1.1 to v10.0.1.

Edit: Can confirm it works correctly in v8.1.1

**Comment by dominic-simplan** [comment]
I think this issue is still valid.

**Comment by louisameline** [comment]
I also sometimes get such a result after a call to `store.get(alias)`.  Most properties are empty. I'm using a test account for the purchase.

I think it happens when I come back to the app after the subscription has expired because Google canceled it (you know, when Google cancels automatically the test after 5 auto-renewals or so).

The JSON stringified product is like this:

![image](https://user-images.githubusercontent.com/371814/108221230-d96ef680-7137-11eb-907c-128f7e514c1f.png)

**Comment by dominic-simplan** [comment]
Still valid
