### ISSUE TITLE
[All Platforms] Feature request - add custom HTTP headers to validation payload

### ISSUE THREAD

**Issue by slothstronaut** [j3k0/cordova-plugin-purchase#1082]
Thanks for the great plugin. It is very well built and documented.

One area I think can be improved is the custom validation URL option is a bit inflexible since you can only pass parameters via query params, i.e. `https://myvalidator.com/custom-validator?token=abc123`.

It would be great for security and fraud prevention to be able to specify custom headers like `Authorization: Bearer xyz`, or `Firewall-Token: abc123` for example to make the request more secure to a custom backend, or to associate the request to an existing user.

I realize it's a bit against your interest, since you have your own paid backend validation service. If I submitted a PR for this, would it likely be accepted? 

Thanks for your consideration

**Comment by j3k0** [comment]
AFAIK, over `https`, for ajax requests, headers aren't more secure that query parameters: they're either all exposed (if there's a man-in-the-middle) or none are exposed.

You can already make custom requests to your validator by setting a validator function instead of the validator URL.

It might be usefull when using some frameworks that require the auth tokens in the headers, so the PR might make sense.
