### ISSUE TITLE
[ANDROID] Consumable are not being acknowledged

### ISSUE THREAD

**Issue by distante** [j3k0/cordova-plugin-purchase#1124]
### system info

Windows 10
Capacitor 2.4
Device: Android 10
Plugin Version: ^10.3.0

### Expected behavior
After call `product.finish()` a consumable product should be acknowledged

### Observed behavior
Consumables are never acknowledged.

### Steps to reproduce
1. Buy a consumable product
2. (optional) Verified
3. Finish the purchased product.

---
The product I am using has this structure:

```
 {
        id: 'my_id_here',
        type: ProductTypes.CONSUMABLE,
        alias: 'my_Alias',
        durationInMs: 100000000,
      },
```
----
I did a little debug and this is never called:
https://github.com/j3k0/cordova-plugin-purchase/blob/c579e871ff3f82d2a57b4bd27f427ad7728ffb02/src/android/cc/fovea/PurchasePlugin.java#L154-L156

I suppose it has something to do this this javascript part where the `CONSUMABLE` part does not have any call to `acknowledgePurchase` ( and not other reference to that function exist)

https://github.com/j3k0/cordova-plugin-purchase/blob/c579e871ff3f82d2a57b4bd27f427ad7728ffb02/src/js/platforms/plugin-adapter.js#L291-L338

**Comment by siauderman** [comment]
Any fix for this? I also want to know how to acknowledge consumable purchases.

**Comment by j3k0** [comment]
Yes, there's no acknowledgement of consumable products because `finish()` will consuming them right away with this:

https://github.com/j3k0/cordova-plugin-purchase/blob/c579e871ff3f82d2a57b4bd27f427ad7728ffb02/src/android/cc/fovea/PurchasePlugin.java#L151-L153

As explained in Android's documentation, consuming will do an implicit acknowledgement.

https://developer.android.com/reference/com/android/billingclient/api/BillingClient#consumeasync

> For one-time products ensure you are using this method (consumeAsync) which acts as an implicit acknowledgement.
