### ISSUE TITLE
[iOS] store.when().cancelled not triggered but give a error

### ISSUE THREAD

**Issue by JamMilk** [j3k0/cordova-plugin-purchase#1142]
### system info

```
Cordova 10.01
Device: iPhone iOS 5.1.1
Plugin Version: 10.5.0
```

### Expected behavior

function inside store.when(product).cancelled() triggered properly

### Observed behavior

I am thesting it in sandbox,
function is not trigger, and give an error:
[store.js] ERROR: ios -> ERROR 6777006: cannot connect to iTunes Store

### Steps to reproduce

click the order button-> click cancel button when asking confirmation

I am so frustrated in the situation as i cannot figure out the problem. The function works fine in android, and if i choose to even if I confirm and purchase in iOS, everything work as expected. Only the cancelled function has problem

**Comment by aMUSiC** [comment]
+1 . It fails here as well on iOS

**Comment by pellaras** [comment]
@j3k0 The issue is [here](https://github.com/j3k0/cordova-plugin-purchase/blob/ca656bc7ab976d5709c85cdfa5c4a583b92a95d8/www/store-ios.js#L3921) and [here](https://github.com/j3k0/cordova-plugin-purchase/blob/ca656bc7ab976d5709c85cdfa5c4a583b92a95d8/www/store-ios.js#L3934).

It tries to compare with error codes under **storekit** instead of **store**.

Can send a PR if it will make it simpler for you

**Comment by philmerrell** [comment]
Seeing this issue as well.

**Comment by j3k0** [comment]
> It tries to compare with error codes under **storekit** instead of **store**.

Good catch, thanks.

**Comment by philmerrell** [comment]
Has anyone else had a chance to test this in `10.5.3` and can confirm it is working on iOS? My preliminary tests show that now it doesn't trigger the `error` or `cancelled` callback if a transaction is cancelled. It used to at least trigger the error callback.

I would gladly be wrong if I am mistaken.
