### ISSUE TITLE
[ANDROID] Product item is not available but succesfull registrered

### ISSUE THREAD

**Issue by paddibr** [j3k0/cordova-plugin-purchase#1171]
### system info

Android
Ionic: 6.12.3
Cordova: 10.0

### Problem

We updated the plugin to version 2 in our app. We registered all products successfully and the store is ready after a refresh.
If we use `this.store.order(id);` to purchase the product, the product is valid and canPurchase is set to true. It is a subscription. But after requested -> initiated it fails after subscripe() with the following info "ITEM_UNAVAILABLE":

```
InAppBilling[js]: subscribe()
store-android.js:2172 [store.js] INFO: plugin -> subscribe error 6777003
purchase.service.ts:103 Store Error {"code":6777003,"message":"Purchase failed: ITEM_UNAVAILABLE"}
```

And PlayStore shows the message "Product not found": 
![image](https://user-images.githubusercontent.com/9463756/109805086-4e0b6000-7c23-11eb-8de4-2be01c7ee82e.png)

**Comment by RyanLefebvre** [comment]
Did you ever find a fix to this? I am currently experiencing the same issue. I can verify the product exists because I print it out after I register it and print it out in the update callback. I get the exact same error code and error message as you. Everything works fine on iOS. 

I know the product id is correct and it matches the id of a product in my Google play console that has a status of active. I've made sure to switch to a different google account than the one I have registered as a developer with google and I am stuck. Any help would be much appreciated because I have poured a lot of time into this issue.

**Comment by paddibr** [comment]
Hi, yes. You have to add your Playstore mail into the app console. Important is, that you use the right mail.

**Comment by j3k0** [comment]
Seems fixed so? I'm closing. Please reopen if you still have the same issue.

**Comment by RyanLefebvre** [comment]
I am still having this issue. But I believe it is because my app was not published in the closed testing alpha track. Instead it was published in the internal testing track as a draft. I have submitted to the Alpha testing track but my app has been marked with a status of 'in review' for about 3 days now. My plan was to comment on this thread again with my results if publishing as an alpha did not work but I am still waiting to see. 

The following [medium article](https://medium.com/bleeding-edge/testing-in-app-purchases-on-android-a6de74f78878) helped me identify some things that might be causing my issue, but as far as I can tell, I followed the[ documentation](https://purchase.cordova.fovea.cc/use-cases/subscription-android) on android auto renewing subscriptions perfectly. 

If someone could confirm or deny that my app must be reviewed and approved in the alpha track for these subscriptions to appear in the native google play store dialog, that would be appreciated. It is my first time building an android app, so I am still getting used to working with some of the tools.

**Comment by VicEsquivel** [comment]
@paddibr where do you mean by saying "into the app console", you mean the Google Play console testing group emails? 

I'm having this same error, my app is unpublished right now, because I am lacking some documentation, but in the meantime, I would like to implement this IAPS module, but I keep getting the error ```chromium: [INFO:CONSOLE(2173)] "[store.js] INFO: plugin -> buy error 6777003", source: file:///android_asset/www/plugins/cordova-plugin-purchase/www/store-android.js (2173)```, and then ```CordovaPurchase: buy() -> Failed: Product not registered:productId```. 

My InAppProducts are with the status of ```Active``` in the PlayConsole since 3 days ago. Also do you have a hint what this could be @j3k0

**Comment by j3k0** [comment]
You need to publish the app to the Alpha track, then builds using the same signing key should have IAP enabled. Check the doc, it's all explained: https://purchase.cordova.fovea.cc/
