### ISSUE TITLE
use Billing Library version 3 or newer.

### ISSUE THREAD

**Issue by brunoalex** [j3k0/cordova-plugin-purchase#1176]
are you guys getting this error ? how to update this ?

Play Billing Library version deprecation
smart cover flip book screen on/off
smart cover flip book screen on/off
24 Mar 2021 00:54
We've detected that this app is using an old version of Google Play Billing. From 1 November 2021, all app updates must use Billing Library version 3 or newer.

Action required: Please verify that your publicly available APKs are updated to the latest version of the Play Billing Library. This includes any APK or App Bundle rolled out in production.

**Comment by boengli** [comment]
I had this message as well, the last two days or so.
Today it "magically" disappeared.

**Comment by j3k0** [comment]
The plugin uses billing library version 3 since `v10.3.0`, cf release notes.

**Comment by henkkelder** [comment]
I am confused. I am using plugin version 10.5.3 but still got this warning. 
Rebuild a couple of times, checked my .APK. Everything seems fine but still the Play Console gives this warning... :-(

Any clues?

**Comment by j3k0** [comment]
Hello,

I'm confused too, seeing this on other apps that don't even use cordova and
are definitely using the latest Billing Library. I'm wondering if it's
because of a version in the Alpha or Beta track?

The plugin definitely use billing library v3, cf plugin.xml

*      <framework src="com.android.billingclient:billing:3.0.0" />*


Regards,
JC

Co-Founder & CTO at Fovea
https://billing.fovea.cc

**Comment by henkkelder** [comment]
Hmm that could be it. 
The version I get the warning on is an open beta, but the production version still uses version 8 or so of the plugin. 
Lets see what happens when I try to publish this version as production version.
That will take some time thought. 
Bedankt voor het antwoord.
