### ISSUE TITLE
[IOS] Crash when trying to purchase item that doesn't exist

### ISSUE THREAD

**Issue by orjandh** [j3k0/cordova-plugin-purchase#1190]
When purchasing a subscription (probably happens for other types as well) that is registered but does not exist in the app store, the app crashes. (This also happens if, for some reason, the iap server doesn't successfully return your items.)

This commit fixes the issue: https://github.com/orjandh/cordova-plugin-purchase/commit/ef87d6201f3f8d71037cfcbcc49cd817120829b6. But it is probably not the best way to handle it because it will now just silently fail. A better way would probably be to add some error reporting.

### system info

```
OSX Big Sur 11.2.3
Cordova: 10.0.0
Device: iPhone iOS 14.4.2
Plugin Version: 10.5.3
```

### Expected behavior

I would expect it to not crash inside StoreKit addPayment function and rather handle this error.

### Observed behavior

Purchasing a registered subscription that doesn't exist causes a crash.

### Steps to reproduce

Register a subscription with a random name that doesn't exist in app store. Then try to purchase it.

**Comment by j3k0** [comment]
As per the documentation, the app shouldn't allow the user hit the `Buy` (and call `store.order(id)`) when `product.canPurchase` isn't `true`. If the app is following this, this crash should never be allowed to happen. This also prevents the user from trying to purchase a product which is already owned, or when there is a pending transaction, or if it isn't allowed to make orders (parental protection) .. which also trigger various types of errors.

"Buy" should be grayed-out and inactive if `!product.canPurchase`, then this crash cannot happen.

The commit still makes sense, as a crash is never a great behavior (even when due to a programming mistake).
