### ISSUE TITLE
Warning from Google Play Console: Play Billing Library Version Deprecation

### ISSUE THREAD

**Issue by retinarisk** [j3k0/cordova-plugin-purchase#1203]
I do apologies if this is a duplicate issue. I have however not seen solutions to previous questions with similar issues. 

I am using cordova-plugin-purchase@10.3.0 (Will upgrade to 10.5.0 for next release).
From /node_modules/cordova-plugin-purchase/plugin.xml . I can see billing:3.0.0
framework src="com.android.billingclient:billing:3.0.0" />

However I have received this warning below from Google Pay Store.

#### Action required: Please verify your publicly available APKs are updated to the latest version of the Play Billing Library. #### This includes any APK or App Bundle rolled out in production.

I do see errors in Sentry.io as well connected to this issue. 
```
ERROR : Store Error: {"code":6777001,"message":"Init failed - Setup failed. BILLING_UNAVAILABLE: 
Google Play In-app Billing API version is less than 3"}

```

From package.json
```
"dependencies": {
...
"@ionic-native/in-app-purchase-2": "^5.29.0",
"cordova-plugin-purchase": "^10.3.0",
...
}
```

**Comment by j3k0** [comment]
`BILLING_UNAVAILABLE: Google Play In-app Billing API version is less than 3`

Google Play Billing Library checks the user's client version and will return this error message if their devices have a very old Play Store installed on their devices. This is a good indicator that your app uses Billing Library v3.

The warning might be there because your have another APK available that uses the old library, in Alpha or Beta tracks maybe? I have seen that error in other apps (using native code too) and confirmed that it uses the Billing Library API version 3.
