### ISSUE TITLE
[IOS] Method store.order doesn't open a native purchase popup

### ISSUE THREAD

**Issue by nagasiNR** [j3k0/cordova-plugin-purchase#1220]
Hi! I have troubles with in app purchases on iOS platform. I successfully register and show subscriptions but after call to store.order nothing happens. It used to worked for me in the first release with purchases but doesn't work on the second one.
And still works on the development environment (a separate App).

I noticed that I started to catch an error: `{ code: 6777020, message: 'Transaction expired' }`
What does it mean? How can I fix it?  Can it be reason of issue?

In docs I found it. I guess this is the error above but there is no explanation
`store.ERR_PAYMENT_EXPIRED     = ERROR_CODES_BASE + 20;`

Remarks:
- Subscriptions are reviewed and approved by Apple
- The latest Licence is accepted in App Store Connect
- Tried this fix `store.autoFinishTransactions = true` - doesn't work for me
- No errors and responses in callbacks of order method (they don't call at all)

Thanks!

Cordova Version: 9.0.0
Cordova iOS: 5.1.1
Plugin Version: 10.5.3
Ionic Native Plugin Version: 4.20.0 (@ionic-native/in-app-purchase-2)
Device: iPhone 8+ iOS 14.6

**Comment by j3k0** [comment]
Can you share some logs from XCode (or Safari developer tools) with `store.verbosity = store.DEBUG`. Thanks

**Comment by ArnauKokoro** [comment]
@j3k0 It seems to be for the state a purchase is. I'm testing the plugin but when something gets wrong inside the approved event, the purchase state stucks on valid and I can't store.order() that product again because the native modal not shows up. I could product.finish() my purchases when store.refresh() and clean the transactions, but now all purchases are owned and I don't know how to change the state to test again store.order() to be able to see the native modal again.

Thanks!!

**Comment by nagasiNR** [comment]
Issue was inside In App Purchases setup and cross environment tests on one device.
Thanks for your time and checking!
