### ISSUE TITLE
[IOS] Ready event not fired

### ISSUE THREAD

**Issue by ArnauKokoro** [j3k0/cordova-plugin-purchase#1248]
### system info
iPhone X iOS 15
Plugin Version: 10.6.0

### Expected behavior
Event Ready fired

### Observed behavior
Event Ready is not fired. Products are loaded and registered but plugin never send ready event.

### Steps to reproduce
When inside device ready callback add =>

`store.ready(() => console.log("READY IN"))`

**Comment by MisterOrrange** [comment]
Same for me, did you manage to solve it?

**Comment by kinggolf** [comment]
I do not think this is a plugin issue, nor an issue with the code. This app has been released since January and nothing in the IAP set up or implementation has changed w/ the latest updates. In fact I can roll back the code to version released to AppStore and see the exact same thing.

Seems to be related to iOS15 and TestFlight or sandbox users, or something along those lines.

**Comment by kinggolf** [comment]
I added manual store.refresh call:
```
⚡️  [log] - refreshStore
⚡️  [log] - [store.js] DEBUG: store.trigger -> triggering action refreshed
⚡️  [log] - [store.js] DEBUG: refresh -> checking products state (3 products)
⚡️  [log] - [store.js] DEBUG: refresh -> product id monthly (monthly)
⚡️  [log] - [store.js] DEBUG:            in state 'registered'
⚡️  [log] - [store.js] DEBUG: refresh -> product id 3_months (3_months)
⚡️  [log] - [store.js] DEBUG:            in state 'registered'
⚡️  [log] - [store.js] DEBUG: refresh -> product id 12_months (12_months)
To Native Cordova ->  InAppPurchase restoreCompletedTransactions INVALID ["options": []]
⚡️  [log] - [store.js] DEBUG:            in state 'registered'
⚡️  [log] - [store.js] DEBUG: store.trigger -> triggering action re-refreshed
To Native Cordova ->  InAppPurchase appStoreRefreshReceipt InAppPurchase251528113 ["options": []]
⚡️  [log] - InAppPurchase[js]: refreshing appStoreReceipt
2021-10-14 16:26:52.444235-0700 App[819:39234] InAppPurchase[objc]: appStoreRefreshReceipt: Request to refresh app receipt
2021-10-14 16:26:52.444504-0700 App[819:39234] InAppPurchase[objc]: appStoreRefreshReceipt: Starting receipt refresh request...
2021-10-14 16:26:52.445237-0700 App[819:39234] InAppPurchase[objc]: appStoreRefreshReceipt: Receipt refresh request started
2021-10-14 16:27:16.164750-0700 App[819:39234] [BackgroundTask] Background Task 2 ("SKProductsRequest"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
2021-10-14 16:27:27.171056-0700 App[819:39234] [BackgroundTask] Background Task 3 ("SKReceiptRefreshRequest"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```
AppStore refresh receipt begins to start, but never finishes.

**Comment by jscssphtml** [comment]
Same Problem here. After refresh or when ordering a product it stucks at 'Product request started'. I testet on serveral devices. This problem only occurs on iOS15.

**Comment by franalt** [comment]
I have the same issue on iOS 15, even on a release version of my application which was working flawlessly. It only ocurrs only on devices running iOS 15. Restarting the device works partialy works, if the purchase fails and you try again you are stuck with the same problem, so its no fix... There seems to be some kind of issue with receipt validation on iOS 15. Anyone managed to find a fix or woraround?

**Comment by kinggolf** [comment]
Hey all. I just downloaded iOS 15.1 and tried IAP w/ no changes to my code since before my post 25 days ago. It worked!! Previously, I was on 15.0.2.

It was a little glitchy, e.g. had to sign in w/ Apple ID twice, but the IAP on TestFlight was successful for me.

I received this message when first powered up the app. I have never seen before, but seems to be related to Sandbox account and has been around.
https://developer.apple.com/forums/thread/125164

**Comment by franalt** [comment]
I can verify iOS 15.1 fixes some things. 

However, there is still an issue with expired subscriptions. 

Upon calling `store.refresh()` i get the following: 

`DUBUG: state: productid -> requested`
`DUBUG: state: productid -> approved`
`DUBUG: ios: -> productid  expired`
`DUBUG: ios: -> productid  owned=false`
`DUBUG: state: productid -> valid`

Calling `store.get(productid).canPurchase` returns `true` but calling `store.order(productid)` get the same output as above, and no purchase window is opened.

Can anyone help me?

**Comment by zvolnix** [comment]
> I have the same issue on iOS 15, even on a release version of my application which was working flawlessly. It only ocurrs only on devices running iOS 15. Restarting the device partialy works, if the purchase fails and you try again you are stuck with the same problem, so its no fix... There seems to be some kind of issue with receipt validation on iOS 15. Anyone managed to find a fix or workaround?

I never had the issue again after that also, when building do you use  --prod tag? I always have issues with this plugin when I use --prod.

**Comment by aliaftech** [comment]
I am having same issue, where testflight works fine and order button does not work on live/production. What I have noticed is that if I click the button leave it sitting for 3 to 4 minutes then it starts working, not sure what is causing it but hard to debug when testflight works and production is showing issue

@j3k0 any idea on how can we fix this issue.

**Comment by aliaftech** [comment]
anyone able to solve this issue?

**Comment by MarcRoemmelt** [comment]
@aliaftech , @franalt This issue can occur when the validator is not completing correctly - usually because a custom method is specified which does not call the callback function.

Note that IOS generates an additional purchase on startup for the app itself (with the product.id === bundleId) even for free apps. Make sure that the callbackFN is also called for this purchase. This purchase does not exist on Testflight or on Android so the error is specific to live IOS apps.

Maybe this could be added the to documentation!

**Comment by aliaftech** [comment]
@MarcRoemmelt thank you for pointing out about the additional purchase.. is there any documentation that you followed for this? I am trying to check what will be correct way to trigger the callback for that purchase..

**Comment by MarcRoemmelt** [comment]
@aliaftech I am not aware of this being documented anywhere. Generally we are simply calling the callback with `true` since the app is either free or paid for if it was downloaded (this might be different if you share ad-hoc builds). 

So just doing `callback(true, transaction)` should be fine in most cases.

**Comment by mayankkataria** [comment]
I'm facing the same issue in android as well

**Comment by firebiird** [comment]
I had this issue for a while. As another comment here has stated, if you have a custom validator you must make sure that you are resolving the callback for all validation requests. you can do this after you check if the product matches yours with a catch all statement of : 
``` 
callback(true, product.transaction) 
```

Please make sure your not giving your hard work away for free before copying this code 😂

**Comment by aliaftech** [comment]
Note that IOS generates an additional purchase on startup for the app itself (with the product.id === bundleId) even for free apps. Make sure that the callbackFN is also called for this purchase. This purchase does not exist on Testflight or on Android so the error is specific to live IOS apps.

this is the main issue

**Comment by alyleite** [comment]
Thanks @MarcRoemmelt and @aliaftech. It worked
