### ISSUE TITLE
[android] - No authentication during purchase

### ISSUE THREAD

**Issue by kevinswartz** [j3k0/cordova-plugin-purchase#1285]
### system info
```
OSX Monterey 12.1
Cordova 9.0.0
Device: Samsung A20 - Android 10
Plugin Version: 10.6.1
```

### Expected behavior
I would expect to receive an authentication prompt during purchase, based on my Android's "Require authentication for purchases" setting:
![Screenshot_20220209-171733_Google Play Store](https://user-images.githubusercontent.com/5995089/153319155-179efd6c-463d-48bc-8001-a4e0ad1aba7b.jpg)

### Observed behavior
Going through purchase is successful, without any authentication.  Toggling this setting does not seem to have any effect.

### Steps to reproduce
Seems to happen with basic steps
```
store.register(getProductIds());
store.refresh();
store.order("my_product");
```

**Comment by bitbay** [comment]
@kevinswartz , this seems like an Android/Samsung update issue. I'm quite sure this is not related to the plugin, since the billing library v3 doesn't expose anything regarding "authentication". It's a mere service any android app can call, and has it's inner and independent settings (working or not).

I recommend closing this issue.

**Comment by kevinswartz** [comment]
Ok thanks for looking @bitbay !  I just wanted to make sure I wasn't missing something.
