### ISSUE TITLE
i am facing this issue while installing the plugin in my new ionic 6 project,

### ISSUE THREAD

**Issue by krunalsk007** [j3k0/cordova-plugin-purchase#1348]
### Observed behavior
# npm resolution error report

2022-12-12T07:00:07.921Z

While resolving: ionic-cordova-app@0.0.1
Found: @awesome-cordova-plugins/core@5.46.0
node_modules/@awesome-cordova-plugins/core
  @awesome-cordova-plugins/core@"^5.45.0" from the root project

Could not resolve dependency:
peer @awesome-cordova-plugins/core@"^6.0.1" from @awesome-cordova-plugins/in-app-purchase-2@6.2.0
node_modules/@awesome-cordova-plugins/in-app-purchase-2
  @awesome-cordova-plugins/in-app-purchase-2@"^6.2.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "@awesome-cordova-plugins/core",
    "version": "5.46.0",
    "whileInstalling": {
      "name": "ionic-cordova-app",
      "version": "0.0.1",
      "path": "D:\\new\\ongoings\\6\\newProject"
    },
    "location": "node_modules/@awesome-cordova-plugins/core",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "@awesome-cordova-plugins/core",
        "spec": "^5.45.0",
        "from": {
          "location": "D:\\new\\ongoings\\6\\newProject"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "@awesome-cordova-plugins/core",
    "spec": "^5.45.0",
    "from": {
      "location": "D:\\new\\ongoings\\6\\newProject"
    }
  },
  "edge": {
    "type": "peer",
    "name": "@awesome-cordova-plugins/core",
    "spec": "^6.0.1",
    "error": "INVALID",
    "from": {
      "name": "@awesome-cordova-plugins/in-app-purchase-2",
      "version": "6.2.0",
      "whileInstalling": {
        "name": "ionic-cordova-app",
        "version": "0.0.1",
        "path": "D:\\new\\ongoings\\6\\newProject"
      },
      "location": "node_modules/@awesome-cordova-plugins/in-app-purchase-2",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "@awesome-cordova-plugins/in-app-purchase-2",
          "spec": "^6.2.0",
          "from": {
            "location": "D:\\new\\ongoings\\6\\newProject"
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false
}

_Include logs with `store.verbosity = store.DEBUG`_

### System Info

Output of `cordova info`.
Ionic:

   Ionic CLI                     : 6.20.4 (C:\Users\kruna\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.2.6
   @angular-devkit/build-angular : 14.2.2
   @angular-devkit/schematics    : 14.2.2
   @angular/cli                  : 14.2.2
   @ionic/angular-toolkit        : 7.0.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 11.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 12 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   Android SDK Tools : 26.1.1 (C:\Users\kruna\AppData\Local\Android\Sdk)
   NodeJS            : v18.12.1 (C:\Program Files\nodejs\node.exe)
   npm               : 8.19.2
   OS                : Windows 10

**Comment by j3k0** [comment]
Hello, in principle you do not need the `awesome-cordova-plugins/in-app-purchase-2` plugin, which is neither developed nor maintained here.

You can simply install `cordova-plugin-purchase` and use the plugin.

**Comment by krunalsk007** [comment]
i installed plugin  as you suggest but now i am facing hoe to used thet in .ts file before this i used  "awesome-cordova-plugins/in-app-purchase-2" to used this plugin so i am able to used all the function using this import like this 
`import { InAppPurchase2, IAPProduct, } from '@awesome-cordova-plugins/in-app-purchase-2/ngx';`
but aftert installing plugin using this direct wy i cant able to used its all function how to used all your funion in .ts file  i try this
but nothing happen  or got an error
```
import 'cordova-plugin-purchase';
declare const { store, ProductType, Platform, LogLevel };
```
or 
import 'cordova-plugin-purchase';
declare const { store, ProductType, Platform, LogLevel } = CdvPurchase;

**Comment by websystems-dev** [comment]
Same here.
The documentation is a bit confusing.
In the official Ionic Framework docs they say to install both (https://ionicframework.com/docs/native/in-app-purchase-2)
```
$ npm install cordova-plugin-purchase
$ npm install @awesome-cordova-plugins/in-app-purchase-2
```
So what is the correct way?
I'm fighting in Android Studio for the last 2 weeks to get it work, without any result, and various errors like
`TypeError: this.store.when(...).registered is not a function`
Any help?

**Comment by j3k0** [comment]
`@awesome-cordova-plugins/in-app-purchase-2` includes typing for the plugin, but they haven't been updated for the latest version. Don't you have access to `CdvPurchase.[something]` typing after installing the plugin?

On a test app, I use this on top of the typescript file:

```ts
/// <reference path="../../plugins/cordova-plugin-purchase/www/store.d.ts" />
```

(`../..` should match the relative path to get to the "plugins" directory from the typescript file)

**Comment by tomingoglia** [comment]
I'm stuck on the same problem...mine with iOS. I haven't tried Android, but I assume we're having the same problem. Running on my native device, the warning indicates that the plugin isn't loaded.
⚡️  [warn] - Native: tried calling InAppPurchase2.DEBUG, but the InAppPurchase2 plugin is not installed.
⚡️  [warn] - Install the InAppPurchase2 plugin: 'ionic cordova plugin add cordova-plugin-purchase'

    "@awesome-cordova-plugins/core": "^6.2.0",
    "@awesome-cordova-plugins/in-app-purchase-2": "^6.2.0",
    
  Just to make sure that other plugins are working, I tried the following and it works fine.
  "@awesome-cordova-plugins/app-version": "^6.2.0",
  
  **Ionic cap sync shows the following:**
  
  Build at: 2022-12-28T21:42:55.296Z - Hash: 803154e864d3a02e - Time: 3676ms
> capacitor sync
[capacitor] ✔ Copying web assets from www to android/app/src/main/assets/public in 584.35ms
[capacitor] ✔ Creating capacitor.config.json in android/app/src/main/assets in 985.00μs
[capacitor] [info] Found 2 Cordova plugins for android:
[capacitor]        cordova-plugin-app-version@0.1.14
[capacitor]        cordova-plugin-purchase@13.1.5
[capacitor] ✔ copy android in 631.02ms
[capacitor] ✔ Updating Android plugins in 6.34ms
[capacitor] [info] Found 4 Capacitor plugins for android:
[capacitor]        @capacitor/app@4.1.1
[capacitor]        @capacitor/haptics@4.1.0
[capacitor]        @capacitor/keyboard@4.1.0
[capacitor]        @capacitor/status-bar@4.1.1
[capacitor] [info] Found 2 Cordova plugins for android:
[capacitor]        cordova-plugin-app-version@0.1.14
[capacitor]        cordova-plugin-purchase@13.1.5
[capacitor] ✔ update android in 48.31ms
[capacitor] ✔ Copying web assets from www to ios/App/App/public in 639.34ms
[capacitor] ✔ Creating capacitor.config.json in ios/App/App in 309.29μs
[capacitor] [info] Found 2 Cordova plugins for ios:
[capacitor]        cordova-plugin-app-version@0.1.14
[capacitor]        cordova-plugin-purchase@13.1.5
[capacitor] ✔ copy ios in 655.59ms
[capacitor] ✔ Updating iOS plugins in 5.21ms
[capacitor] [info] Found 4 Capacitor plugins for ios:
[capacitor]        @capacitor/app@4.1.1
[capacitor]        @capacitor/haptics@4.1.0
[capacitor]        @capacitor/keyboard@4.1.0
[capacitor]        @capacitor/status-bar@4.1.1
[capacitor] [info] Found 2 Cordova plugins for ios:
[capacitor]        cordova-plugin-app-version@0.1.14
[capacitor]        cordova-plugin-purchase@13.1.5
[capacitor] ✔ Updating iOS native dependencies with pod install in 2.00s
[capacitor] ✔ update ios in 2.02s
[capacitor] ✔ copy web in 4.53ms
[capacitor] ✔ update web in 220.08μs
[capacitor] [info] Sync finished in 3.367s

  ─────────────────────────────────────────────────

**Comment by j3k0** [comment]
OK, I know some ionic users are doing without `@awesome-cordova-plugins/in-app-purchase-2` and it seems to work. I have to take a closer look at Capacitor, as there has been request to publish this plugin as a native Capacitor plugin, which is an option I'll consider as it would make things simpler, I'll evaluate both options.

**Comment by websystems-dev** [comment]
Thanks for your suggestion @j3k0 but I need a little help more, because I'm still unable to get WHICH typescript file should have this on its top: 
`/// <reference path="../../plugins/cordova-plugin-purchase/www/store.d.ts" />`
Do you mean inside the in-app-purchase-2 typescript file or somewhere else? Did you add it before or after building the Android (or iOS) project?

In the meanwhile, I found a **dirty** way to have it working.
I'm using the `--force` option while installing old versions of both plugins via npm.
These versions are working for me now (with latest versions of ionic and capacitor):
```
npm i @awesome-cordova-plugins/in-app-purchase-2@5.41.0 --force
npm i cordova-plugin-purchase@11.0.0 --force
```
However I'm aware this is not a best practice to bypass version's dependence, so I really hope to have it working in a clean way.
Thank you so much for your support.

**Comment by tomingoglia** [comment]
@websystems-dev ...you shouldn't need the --force. That just forces a download from the remote source, skipping your cached version. In the present situation, you should be specifying versions are you are since the dependencies are out of sync. If you don't specify versions, you struggle in the future because if in-app-purchase-2 becomes compatible, then it would break due to the @11 on this package. So, until this is corrected, being specific is the best option and watch both repos for updates.

**Comment by tomingoglia** [comment]
> OK, I know some ionic users are doing without `@awesome-cordova-plugins/in-app-purchase-2` and it seems to work. I have to take a closer look at Capacitor, as there has been request to publish this plugin as a native Capacitor plugin, which is an option I'll consider as it would make things simpler, I'll evaluate both options.

@j3k0 A native Capacitor plugin would be ideal. It is certainly possible to use your library without the Capacitor package. You can just npm install it and access it as your examples show. Installing the typings would be needed for those utilizing TypeScript.

There are, however, a lot of videos, blogs and other resources out there with examples using this Capacitor package and those are all broken now with your new release. Both broken and not with an ideal error message making it a multiple hour journey to understand what has happened. At minimum, I'd suggest that you coordinate with @danielsogl who is the maintainer of all of the @awesome-cordova-plugins. I did create an issue over there to help folks as well. 

Ionic and/or Capacitor are the leading tools right now to develop new Cordova/WebView type applications. My guess is that this will become more of a headache for everyone over time.  

Since this isn't resolved, does it make sense to leave this issue open for a while until the docs are updated? Even a note in your docs would be super helpful for folks who are struggling. Maybe even a big note about the major breaking change in v13 right at the top?

Thanks for the quick replies and the awesome plugin!

**Comment by websystems-dev** [comment]
> @websystems-dev ...you shouldn't need the --force. That just forces a download from the remote source, skipping your cached version. 

Nope., --force litterally _forces_ npm to download the version you specified despite a dependency conflict.
For example, if you try to download 
`npm i onesignal-cordova-plugin@3.2.0`
(without --force) you can get this output:
```
npm ERR! Could not resolve dependency:
npm ERR! peer @awesome-cordova-plugins/core@"^5.1.0" from @awesome-cordova-plugins/in-app-purchase-2@5.41.0
npm ERR! node_modules/@awesome-cordova-plugins/in-app-purchase-2
npm ERR!   @awesome-cordova-plugins/in-app-purchase-2@"^5.41.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @awesome-cordova-plugins/core@5.46.0
npm ERR! node_modules/@awesome-cordova-plugins/core
npm ERR!   peer @awesome-cordova-plugins/core@"^5.1.0" from @awesome-cordova-plugins/in-app-purchase-2@5.41.0
npm ERR!   node_modules/@awesome-cordova-plugins/in-app-purchase-2
npm ERR!     @awesome-cordova-plugins/in-app-purchase-2@"^5.41.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
Then using --force you'll override peer dependency. 
Cache has nothing to do with it.

**Comment by tomingoglia** [comment]
I think perhaps you have a couple of different issues going on in your project.  I'm not sure how onesignal is playing in here...but why are you trying to install a specific version? Since we're commenting on issues with cordova-plugin-purchase, it might be best to isolate around those specifics here. 

In your case, --force is trying to pull down a specific dependency that has conflicts with a newer dependency.  I only specified a version for `cordova-plugin-purchase` and it doesn't have any of the dependencies that you are struggling with above. You are struggling with conflicting `@awesome-cordova-plugins` dependencies on the core module. Can you bring all of those current?

I'm on `"@ionic/angular": "^6.1.9"`

**I was able to do:**
`npm i @awesome-cordova-plugins/core`
`npm i @awesome-cordova-plugins/in-app-purchase-2`
`npm i cordova-plugin-purchase@11`

**As a result I have:**
`"@awesome-cordova-plugins/core": "^6.2.0",`
`"@awesome-cordova-plugins/in-app-purchase-2": "^6.2.0",`
`"cordova-plugin-purchase": "^11.0.0",`

**Comment by krunalsk007** [comment]
i was able do install this plugin ` ionic cordova plugin add cordova-plugin-purchase --force   `    if you have any cache issue than 

```
npm cache verify
npm cache clean --force
```

for used this plugin import thsi plugin in your ts file
```
import 'cordova-plugin-purchase';
declare const CdvPurchase: any;
```

and the use like this
```
 CdvPurchase.store.register([{
        id: productId[0],
        type: CdvPurchase.ProductType.PAID_SUBSCRIPTION,
        platform: CdvPurchase.Platform.GOOGLE_PLAY,
      }, {
        id: productId[1],
        type: CdvPurchase.ProductType.PAID_SUBSCRIPTION,
        platform: CdvPurchase.Platform.GOOGLE_PLAY,
      },
      ]);
```

**Comment by tomingoglia** [comment]
@krunalsk007, Maybe I'm mistaken, but I don't think you can install a Cordova plugin using `add` if it is a Capacitor project. Does `--force` make that work or are you in a Cordova project?

Do you get typings with your method? Perhaps no with `CdvPurchase: any;`?

**Comment by krunalsk007** [comment]
sorry but i am using cordova in my project.
