### ISSUE TITLE
missing transaction properties, variable initialization 

### ISSUE THREAD

**Issue by aegluke** [j3k0/cordova-plugin-purchase#1356]
### Observed behavior

with v13 i have two problems. the transaction.products did not contain the product id for apple in app purchases. only the bundle-id of the app.

second problem: applicationUsername must be initialized, or the native code of the exception. so i have to initialize it with ''.

### Expected behavior
i need the purchased poduct inside the transaction.

### System Info

i use the latest capacitor version.
latest xcode version
latest ios version

**Comment by j3k0** [comment]
The `applicationUsername` issue is fixed with e53017c.

With AppStore, there will be a single transaction containing details about the "application download".

If you make purchases, you should see more transactions. Note that consumable transactions are removed from the receipt after the app is restarted, only the last transaction for a subscription is returned. Can you provide more information: in particular logs from a session where you place a purchase, with DEBUG verbosity.

**Comment by cozyop** [comment]
yes, the function does not return transaction info at all

**Comment by j3k0** [comment]
I can't help without debug logs from the app, which haven't been provided after 50 days, so I'm closing the issue.
