### ISSUE TITLE
[Android] v13 .approved() triggered immediately after .initialize() completed

### ISSUE THREAD

**Issue by Calsy** [j3k0/cordova-plugin-purchase#1391]
Would there be any reason for .approved() to be triggered after completing .initialize()? I can't seem to stop this event from firing. Has anyone else experienced this issue?

**Comment by j3k0** [comment]
It's not an issue, it's by design.

`.approved()` will be triggered for active purchases at startup (subscriptions and non-consumables).

In the general case, you will call `verify` so your receipt validation service will check the validity of the purchase, if it's been canceled or refunded, etc.

The idea is that:

1. Doing that, you're also handling pending purchases with the same code.
2. You shouldn't blindly trust what's reported by client side SDK: some people will try their luck with "patcher" apps to get in-app purchases for free.
