### ISSUE TITLE
store.initilize and store.update does not update if product is owned

### ISSUE THREAD

**Issue by maxfloden** [j3k0/cordova-plugin-purchase#1470]
This is just a minor thing but it is a little confusing and took me a while to figure out, not sure if it is working as expected or not?

### Observed behavior
I just upgraded from v11 to 13.8.0 and noticed this:
* store.initialize() does not update "owned" info, ie I cannot determine if something was already purchased (NON_CONSUMABLES in my case)
* store.update() - if I run this after initialize this also does not update "owned" info
* store.restorePurchases() - this does update "owned" info (so I now use this after initialize)

### Expected behavior
* Reading the [migration guide for v13 ](https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO:-Migrate-to-v13) I would think store.update should work to get me updated "owned" information
* store.update does not run after store.initialize without also changing default value of store.minTimeBetweenUpdates, so this made me think initialize already updates but it does not 

From migration guide:
```
store.refresh() is now store.initialize()

The store.refresh() method had 3 different purposes:
initialize the plugin
refresh product prices and status of purchases
restore purchases (on iOS)

The plugin now has one method for each of those purposes:
use store.initialize() at initialization
use store.update() to refresh product prices and status of purchases
use store.restorePurchases() to restore purchases
```
### System Info
* Ionic 7 / Angular 16 / Capacitor 5
* Plugin 13.8.0

**Comment by lincolnthree** [comment]
I am also seeing an issue like this. However according to Apple we are apparently not supposed to call "store.restorePurchases()" automatically because it will prompt the user for their App Store / iCloud credentials.

What is the correct sequence of calls to get updated receipt info on App Startup?

**Comment by j3k0** [comment]
Yes, store.restorePurchases() should only be called in response to the user clicking a "Restore Purchases" button in your app. In general, it will ask the user for their AppStore password, then replay the entire history in transactions. It's only meant to recover from certain situation, not meant for normal use.

The `owned` status of your products should be correct, it's been well tested on non-consumables. Can you share logs and source code? Is the issue resolved?

**Comment by lincolnthree** [comment]
It turns out that situation for us involved the user attempting to make a purchase, but the bank declining the purchase via the Apple App Store. Apparently once the user called their bank, they were able to complete the purchase (and we received the populated `in_app: [ ... ]` array as expected.

I'm not 100% sure how we're supposed to know how to handle that scenario.

**Comment by lincolnthree** [comment]
Actually not sure this is exactly what's happening. It seems the value of `in_app:[]` is being omitted somewhat randomly. I can't pin it down.
