### ISSUE TITLE
[IOS] [TestFlight] Buy/Restore problem with 2 devices

### ISSUE THREAD

**Issue by hooliapps** [j3k0/cordova-plugin-purchase#1554]
Hello

I'm tring to test In App Purchases update with TestFlight with 1 iphone and 1 ipad (same email icloud).

1. On iPhone (OK)
- I buy the auto-renew purchase
- Activation is OK
- I delete the app, then reinstall
- When i start Store, the buy is auto re-activated: OK

2. On the ipad (not ok)
- I start store, nothing
- I click Restore purchase, nothing
- I click "Buy" button, then i see a message : I already own the subscription, and i cannot buy it anymore / neither restore

Do you know please if this problem can be due to TestFlight ? Or plugin ?

* I use cordova-plugin-purchase since 2018, now version 13.10.1

Code:

function initStore() {
storeUrl = iapFoveaValidator;
CdvPurchase.store.validator = storeUrl;
CdvPurchase.store.register([{.... products
	CdvPurchase.store.ready(function() {
		console.log('CdvPurchase.store.ready()');
	});
}

	CdvPurchase.store.when().approved(function(transaction) {
		
		console.log('CdvPurchase.store.when().approved(transaction)');
		
		if (isIOS) {
			if (transaction.products && transaction.products[0] && transaction.products[0].id === '%THEID%') {
				transaction.finish();
				return;
			}
			if (transaction.state === 'approved') {
				transaction.verify();
			}
		}
		else {
			transaction.verify();
		}
		
	});

function storeRestorePurchases() {
	CdvPurchase.store.restorePurchases();
}

**Comment by hooliapps** [comment]
Hello, do you have news of the subject please ?

**Comment by j3k0** [comment]
Do you have some logs of what happens when the user clicks "restorePurchases"? It should do the job (assuming the user is logged in with the same appstore account).

If you want purchases to be automatically restored, you should probably verify also the application receipt, so purchases added without user intervention are picked up automatically (purchases already present at startup, added from a different device, family shared purchases, etc).

Getting rid of the `if (transaction.products && transaction.products[0] && transaction.products[0].id === '%THEID%') {` should probably fix it.

If what you want is minimize the number of "empty" receipt validation calls, you can threshold that in some way. For example, store `lastAppReceiptValidationDate` in localStorage, update the value when you call `verify()`, then only verify your app transaction when `lastAppReceiptValidationDate` is unset or older than X days.

**Comment by hooliapps** [comment]
Hello

I launch the process only after user click Restore buttons.

I will retry that asap and i will provide new logs.


Best regards

**Comment by hooliapps** [comment]
Hello

I removed the transaction.products[0] part, then Purchases was correctly
restored, but i still have a problem (only on my iOS Account with
TestFlight + Direct usb connection to XCode), app Crash after restore.

CdvPurchase.store.when().approved(function(transaction) {
transaction.verify();
});

CdvPurchase.store.when().verified(function(receipt) {
receipt.finish();
...
});

Seems "approved" then "verify" are launched for a lot of elements.

Do you know please if there is a way to only launch the process for last
"Auto renewable subscription" ?

Best regards
Alexandre

[image: image.png]
