### ISSUE TITLE
Question about possibility to clear transaction history on the phone locally

### ISSUE THREAD

**Issue by v-trishyn** [j3k0/cordova-plugin-purchase#1603]
Hello.
I can remember v11 had a function to remove previous purchase history. 
Currently I'm having a problem with too much calls of `.approved()` listener, well I used debug a lot and got many transactions in time. While my backend can count 56 calls, frontend also shows too much of calls in the `.approved()`.
And now for some reason old sandbox account can't subscribe without problems - the time to show the app store popup is too long.
While the new sandbox account is working okay and fast. 
It is an issue because iphone provides a limited amount of sandbox users to be logged into 1 iphone.

And I couldn't find this anywhere now, but maybe I'm missing it.
@j3k0

**Comment by j3k0** [comment]
>  v11 had a function to remove previous purchase history.

I don't think so, because this doesn't exist in the native SDK. Maybe you are referring to the `autoFinish` option (to finalize pending transactions?)

https://www.iaptic.com/documentation/cordova-plugin-api/interfaces/CdvPurchase.AppleAppStore.AdapterOptions.html#autoFinish

```ts
CdvPurchase.store.initialize({platform: CdvPurchase.Platform.APPLE_APPSTORE, options: {autoFinish: true}})
```

Make sure you are not calling `restorePurchases` (which shouldn't be done unless the user hits a "restore purchases" button in your app).
