### ISSUE TITLE
Consumable product keeps showing already purchased

### ISSUE THREAD

**Issue by aidansalvi** [j3k0/cordova-plugin-purchase#166]
I have created a consumable product and have purchased it via a sandbox user. The next time I purchase the product it show it has already been purchased. Not sure if anyone has face this issue.  Has anyone been able to make consumable products fully work?

**Comment by butlimous** [comment]
I have this as well and don't know the solution

**Comment by aidansalvi** [comment]
The problem is that is hasn't been finished. Use the store.finish() call
with no other code. Let it finish and then it will work the next time.

On Friday, May 1, 2015, butlimous <notifications@github.com> wrote:

> I have this as well and don't know the solution
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j3k0/cordova-plugin-purchase/issues/166#issuecomment-98191896>
> .
>


-- 
Thanks!
Aidan Salvi
847.778.8975

**Comment by butlimous** [comment]
Tried this as well but it does nothing. The product returns a state of valid and canPurchase is true. However when calling the store.order to initiate a purchase, the state changed to requested then initiated with canPurchase as false! and the error that product is already owned popups :(

**Comment by butlimous** [comment]
Figured out :) I was testing the behavior if the internet connection fails in the midway after the user actually clicks the buy button to buy the product and it's being processed. So what happens is that an error will popup that there is no internet connection. However, the user will get the receipt that they made a purchase. The state of the product return backs to "Valid" and doesn't pass through the "Approved" or "Owned". So when trying again to order the previous transaction is actually stuck that's why it says product already owned although state is "Valid". After around 1 hour, getting the state again will process the order and pass from "Valid" to "Approved" and then you have to call the "Finish" method to make the product available again for purchase.

**Comment by mehmetkoc182** [comment]
I'm having the same issue but I can't get past this stuck stage.
I tried finishing the order which is what most threads about this issue says so. 
Finishing does put the product back to valid state from initiated but when I try to purchase again, I get the same product already purchased modal.

So your solution was to wait an hour and then try to finish the order?
