### ISSUE TITLE
Auto renewing subscriptions

### ISSUE THREAD

**Issue by mariusk** [j3k0/cordova-plugin-purchase#177]
I'm seeking advice/documentation on how this is actually supposed to work. I have successfully implemented this for my app for App Store (sandbox mode), but I am seeing some issues. It is also a royal PITA to debug, because I have to build in "release mode" to test IAP, which means traditional debugging through the Safari remote debugger does not work. So I'm using "alert" boxes.. _sigh_ Suggestions on how to improve the debugging experience are welcome!

I've been able to subscribe to a monthly subscription product for my app. For some reason, I seem to have been able to do this four times now, but all subscriptions have expired (in sandbox mode one month typically equals 5x5 minutes or so). This means my custom validator fires up four times and makes four requests to my server (which again contacts Apple's server); this seems necessary as verifying the receipt seems to be the only way to figure out if the subscription has actually expired.

Is this assumption correct?

To avoid this event happening repeatedly in my app, I seem to be able to "mutate" the product objects returned by the callback, setting a `product.expired = true;` for products that actually expired. I can then use this member to avoid having my validator repeatedly calling back to my server again the next time a `product.refresh();` is done.

Is this a "proper" way to use this plugin, or are there better ways?

When I find no active (non-expired) subscriptions I would like to offer the user to resubscribe to that product. But none of the products from that type of product have the `canPurchase` flag set. From reading various articles about this, this may very well be a "feature" of auto renewing subscriptions in the app store?

Is this a limitation with auto-renewing subscriptions in the App Store?

Finally, I also tried to find my active subscriptions on my phone, but no "Manage Subscriptions" button appear where expected.

Is the missing "Manage Subscriptions" button a feature of sandbox mode, and if so, does anybody know if the option to resubscribe would typically appear there when in non-sandbox mode?

**Comment by mariusk** [comment]
Having read up on the subject, I do not believe this module is ready to use with auto-renewing subscriptions, at least not if you need to be able to test using sandbox users first. The combination of "issues" with auto-renewing subscriptions in test-mode (renews automatically five times, then you need to add a new test user to be able to test again) combined with the caching this module uses makes it currently impossible to test with a new user; the same old "expired" receipts will be received also for any new test user added in iTunes Connect.

**Comment by mariusk** [comment]
I'll add to this that the whole sandbox environment and IAP testing process on Apple is seriously difficult to use. When/if you google it it's related to "broken test users", where depending on what you do with a test user, it may become "broken". A "broken" test user will lead to the normal callbacks (delegates) in your application not being called properly. Another issue is which iTunes user is the app on your device or simulator actually logged in as? On the simulator, you can do "Reset Content and Settings" to start fresh, but on your device that might be harder to accept. After a reset, the app will prompt you to log in with your iTunes user (test user) as soon as you do a call to "restoreCompletedTransactions" (the StoreKit call, not directly related to this plugin). That is unless your test user is broken (if so, delete and recreate it or create a new one).

**Comment by jwebcat** [comment]
use adb to debug signed apk you can do from shell `adb logcat -s chromium` if you are using crosswalk

**Comment by GuidoAppedemic** [comment]
@mariusk  i was browsing the issues tickets and stumbled upon this thread. It seems like you know a lot about the auto renewing subscription. I have a problem on ios with registering the (type: store.AUTO_RENEWING_SUBSCRIPTION) product. Would you maybe have a few minutes to read my thread? -> #487

**Comment by vreemt** [comment]
the 5mins is expected behaviour of Apple's "Sandbox" environment. it only tries 5 times and then expires. it's not mentioned in the docs, but I assumed the 5mins were so that you can turn off Auto-renew. I'm not sure what else you can test with it

also consider the following details: 

* from this plugin's readme:  product `id` and `type` have to match products for your App in iTunes Connect
* sandbox users *CAN'T* be updated - create a new user to use modified details - source: https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/SettingUpUserAccounts.html#//apple_ref/doc/uid/TP40011225-CH25-SW10 (recent)
* Don’t enter test account information in the Store settings panel - source: https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnectInAppPurchase_Guide/Chapters/TestingInAppPurchases.html#//apple_ref/doc/uid/TP40013727-CH4-SW1
* If you mistakenly use a sandbox tester account to log in to a production environment, the sandbox account becomes invalid - source: https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/SettingUpUserAccounts.html#//apple_ref/doc/uid/TP40011225-CH25-SW10
* IAP FAQ https://itunespartner.apple.com/en/apps/faq/In-App%20Purchases_Auto-Renewable%20Subscriptions 
	* Subscription - publication name is subject to review, won't be changed until it's been reviewed
	* Auto-renewable subscriptions are based on the calendar date
	* The product ID character limit is 255. Product ID and In-App Purchase type cannot be edited once your In-App Purchase has been created.
	* Your app's first In-App Purchase must be submitted for review with the app version. To submit your In-App Purchase with the version of your app, your app must be in the Prepare for Submission state. 
* remember to click 'Save' and 'Done' at the relevant stages	


I agree with you on the whole thing being a PITA. the docs are ambiguous, in most places outdated and contain circular references. the process requires multiple steps and pre-requisites they don't warn you about until you're knee deep in the tasks...
