### ISSUE TITLE
when for multiple products

### ISSUE THREAD

**Issue by chrisschaub** [j3k0/cordova-plugin-purchase#178]
Can you watch multiple products with "when"? Or do I just start the watching cycle when somebody starts the ordering process? I have 4 or 5 products and am just working on the code setup with angular. Thanks for any advice.

**Comment by cameronbourke** [comment]
hey @chrisschaub, you just start the watching cycle when somebody starts the ordering process. When you call `store.order('productId')` then you can listen to different events in the life cycle using `when`. Hope that helps.

**Comment by cameronbourke** [comment]
Also. Use "when" its your product is a consumable, whereas use "once" if it is a subscription or non_consumable. They are the same, expect once registers the callback once the life cycle is over.

**Comment by HimanthTag** [comment]
Will store.off() unbinds all the listeners in this case? I am testing buying multiple consumable products in ios, i am getting it working only for the first time. Since am using angularjs, i have the store related code in my controller, not sure if its the right place to put it in. Any code sample is much appreciated, thanks in advance.
