### ISSUE TITLE
store.off

### ISSUE THREAD

**Issue by chrisschaub** [j3k0/cordova-plugin-purchase#200]
Do I have to call store.off for each "when or once" that I registered? Or can I call it as just store.off and unregister all when's with one command? Also, every time I hit my store page on Android, it calls "approved" for my owned products which means that they start downloading again! It seems linked to calling refresh. I can see the state going from approved to owned, btw. I am calling product.finish(). Not sure if it's related to this.
https://github.com/j3k0/cordova-plugin-purchase/issues/108

iOS doesn't behave this way.

**Comment by j3k0** [comment]
Solved it?

**Comment by chrisschaub** [comment]
Sorry, mis-clicked! So, I see the product "finish" on Android. Every time I go to my store page in my angular app, I call store.refresh (maybe that's wrong?). Anytime I call store.refresh it tries to restore purchases which seems weird. I would think that letting the user opt to do that would be better? iOS seems different here, doesn't try to restore on re-fresh, but maybe it does, gonna test some more. These are non consumable products.

**Comment by chrisschaub** [comment]
Ok, so I just re-read store.refresh docs. It says that I have to call it to finish the store init, but when I do that it also tries to restore all purchases. This seems a bit strange. I get needing to query the product data from the stores, but wouldn't it be better to let a store just change their product display to show purchase or restore based on the owned status? We have a lot of products and it seems strange to just auto restore upon visiting the store page? Especially for non-consumables. Now, I'm using "when" instead of "once" to register the update callback, but that seems ok for non_consumables?

**Comment by chrisschaub** [comment]
Ok, looking more at the code. It doesn't really make sense to me to auto-restore NON_CONSUMABLE purchases on store.refresh(). I can see it make sense for CONSUMABLE, but NON_CONSUMABLE are things like purchased data or unlocking features. Am I missing something, I just don't get why the auto-restore on refresh. It behaves like a bug when used in the app. For Consumables, I can see the design decision, put back what should be there.

**Comment by Alphatiger** [comment]
for type paid subscription i am seeing,  [store.js] DEBUG: android -> consumable finished
and then the product is owned, is this expected, Because for paid subscription once the product is owned it should be the its final state, but after app reload it is triggering approved state. 
Tried many things google play cache clear, device change, mobile restart etc..

What is the type paid subscription expected behaviour?

**Comment by uxder** [comment]
Same issue (Android)... I'm calling store.refresh() on non-consumable products.  On loading my app, an already previously owned non-consumable product, updates with a owned = false, state = "approved", which re-triggers my product update code everytime.

My only work around is to maintain my own persistance so that I can bypass the multiple approved states.  In my case, I check if the product is already downloaded to my app, which by nature indicates that they already own it.

It would be nice if the behavior of this library can be modified so that once a product is owned, store.refresh does not go through a sequence of valid -> approved -> owned and instead just goes straight to owned.

```
    store.when(productId).approved(function(product){

       if(!isDownloaded()) {
        downloadContent(function() {
                product.finish();
        });
      }
    });
```
