### ISSUE TITLE
Send secure nonce with orders

### ISSUE THREAD

**Issue by BrunoMarchesson** [j3k0/cordova-plugin-purchase#202]
Hello,

Is it possible to send a secure nonce with the order and get it back with the validated purchase?

According to Android "Security and Design" guidelines (https://developer.android.com/google/play/billing/billing_best_practices.html), it provides a good protection against replay hack.

I know it is possible on Android side (using developer payload), but I have no idea if the Apple purchase process allows the developer to send a custom value with the order and send it back with the purchase.

Best Regards

**Comment by rwillett** [comment]
I don't believe you can add the nonce to the order to Apple. I'm not an expert here but haven't read anything that says you can. 

Our view was that we look at the store receipts and the validated response from the sandbox and work through there to check validity. Since Apple allows multiple devices per user, we can have multiple receipts, though each of them should be different. I believe Apples view is that a nonce is not necessary as you should be able to do everything with the receipt and the validated JSON response.  I'm not an expert enough to refute that argument.

Rob
