### ISSUE TITLE
cordova plugin add installs 3.10.1 version instead of 3.11.0

### ISSUE THREAD

**Issue by bobibt** [j3k0/cordova-plugin-purchase#209]
I have installed this plugin before, but i like to update it to the current newest version. When i try to add it, it installs the previous older version 3.10.1.
I tried to create a new project but the result is same, it installs 3.10.1. Please help. :)

**Comment by j3k0** [comment]
Tried with latest cordova (5.0) ?

Version `3.11.0` uses the new distribution method (using npm).

**Comment by RouR** [comment]
cordova 5.1.1
in npm lugin version 3.10.1

**Comment by markie040** [comment]
+1

**Comment by artistika** [comment]
Now when i try to work around that problem, with manually adding the store key, i get build error that says String/billing_key_param used more than one time. Can you please help me fix this issue.

**Comment by RouR** [comment]
my workaround is manualy edit .java file - replace method getBase64 to constant. (don`t forget copy modified file to /src/platform/android)

**Comment by artistika** [comment]
I think better way to do that is just change the android.json $BILLING_KEY with the value. I haven't tested it yet but it should work because the res value now is ok.

**Comment by rafaellop** [comment]
I can confirm that the default installation installs 3.10.1 instead of 3.11.0. However, you can force the 3.11.0 installation by calling it with parameter: `cordova plugin add cc.fovea.cordova.purchase@3.11.0 --variable BILLING_KEY="MIIB..."`

One more thing to report. If the new android platform is used (I've got Android 4.0.2) the build process complains about missing translations for the BILLING_KEY. A solution is to add the `billing_key.xml` to each languages folder under `/plaftorms/android/res/values_LANGID` or just modify the default `billing_key.xml` to make the lint ignore the translation checks. To do this just replace the `<resource>` in the xml file with `<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation">`


`

**Comment by j3k0** [comment]
@rafellop issue fixed by 6fa2149

**Comment by RouR** [comment]
version check http://plugins.cordova.io/#/search?search=cc.fovea.cordova.purchase
