### ISSUE TITLE
Is any event fired after store is refreshed?

### ISSUE THREAD

**Issue by andreassh** [j3k0/cordova-plugin-purchase#228]
In this specific case I'm implementing a restore functionality, but can't seem to find any callbacks in your docs for when the store is refreshed?

**Comment by cameronbourke** [comment]
@andreassh There is no callback for when the store is refreshed. The closest you can get to that is when `store.refresh()` is called it will load your products from apple's servers. You can then attach a query to the products like so
```
store.once('product').loaded(function(){..})
```

That way you'll know when the store has refreshed because the products will have been loaded.

**Comment by Gerarddus** [comment]
Actually there is a callback you can hook in to. Like this:
```javascript
store.when("refresh-completed", function(){...} );
```
Take a look at storekitRestoreCompleted() in ios-adapter.js for it's origin.

**Comment by asprotte** [comment]
Ok thanks @Gerarddus . I'll try it out

**Comment by Alveoli** [comment]
Does this callback work on Android?

**Comment by Gerarddus** [comment]
No because as far as I know Android doesn’t do anything with this restore functionality.
