### ISSUE TITLE
Where is Apple Hosted Content Downloading

### ISSUE THREAD

**Issue by gfragioud** [j3k0/cordova-plugin-purchase#280]
Download starts and finishes properly.
Then I list documentsDirectory but there is nothing related to content of purchased product.
So, I believe that something goes wrong during transfering content to documentsDirectory...

The content of hosted product is a folder named as product-id which has inside other folders, images and some text files...

Any idea???

**Comment by G3n3ralTao** [comment]
You were able to download Apple hosted Content?

I get errors when I set event listener on downloading and downloaded. Even if I got hosted content send and verified on my InApp I cannot get it to download it. How did you proceed? What version are you using?

**Comment by dpa99c** [comment]
I'm using the Apple Hosted Content functionality of this plugin in several production apps ([such as this one](https://itunes.apple.com/us/app/iwalk-north-cornwall/id739048330?ls=1&mt=8)); it definitely works, but needs to be configured properly.

@gfragioud Make sure that in your In App Purchase project, you've [created references](https://developer.apple.com/library/ios/recipes/xcode_help-structure_navigator/articles/Adding_an_Existing_File_or_Folder.html) for the content folder/files in the XCode project as well as placing them in a sub-folder inside the project. Since you have all of them in a sub-folder named as the product ID, you'll also need to add a `<Folder>` key to the project plist which specifies this as the root folder - see the [plist](https://github.com/dpa99c/cordova-plugin-purchase-demo-ios-hosted/blob/master/nonconsumablehosted1/nonconsumablehosted1/ContentInfo.plist) in the [example IAP project](https://github.com/dpa99c/cordova-plugin-purchase-demo-ios-hosted/) which also does this.

I'd suggest debugging your issues by enabling debug mode in the plugin. To do this, set `store.verbosity = store.DEBUG;` before calling any other `store` functions. Then run the app via XCode to see the Objective-C debug output in the XCode console. You should then be able to see exactly what the plugin is doing with the hosted content files.

@G3n3ralTao Check the version of the plugin you are using. 3.11.0 is the latest.

**Comment by G3n3ralTao** [comment]
@dpa99c My plug-in is at version 3.11.0, but no download. I posted an issue about it yesterday, but no response so far (https://github.com/j3k0/cordova-plugin-purchase/issues/281)

**Comment by gfragioud** [comment]
@dpa99c thank you very much for your response but I am still struggling with this.

Unfortunately I can't run the app via xcode because I am using appgyver steroids and they don't support local build yet.

With my custom logs I get the below clues:
1) .progress stops always at 80%
2) .downloaded is called (why? it never reaches 100%)
3) documentsDirectory is same both previous & after the purchase. Nothing related to product contents
4) before  purchase, cacheDirectory has only a folder named as my app bundle ID. After the purchase, I see a zip file with a 32(hexa)digit for name and one named http_localhost_0.localstorage.
  
Additionally, the structure of my in-app product is similar to demo (also Apple accepts it without any error), so I think that the problem is inside plugin and not in product.

**Comment by dpa99c** [comment]
@gfragioud 

> Unfortunately I can't run the app via xcode because I am using appgyver steroids and they don't support local build yet.

Without being able to see Objective-C debug output, it is hard to know what the exact problem is.

> 1) .progress stops always at 80%
> 2) .downloaded is called (why? it never reaches 100%)

The .progress() callback is invoked directly by the native iOS StoreKit framework when the product download state is [SKDownloadStateActive](https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/ios/InAppPurchase.m#L715). The progress percentage is generated by the StoreKit framework, not by the plugin. The plugin is simply passing along the information passed to it by StoreKit, which is what performs and monitors the download from the Apple servers. StoreKit doesn't invoke SKDownloadStateActive when the download reaches 100%, it invokes [SKDownloadStateFinished](https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/ios/InAppPurchase.m#L756), which in turn calls (.downloaded()). So in practice, .progress() will not be called when download reaches 100%, it will only be called on the preceding percentage step. It's up to you how you handle this in your app.

> 3) documentsDirectory is same both previous & after the purchase. Nothing related to product contents
> 4) before purchase, cacheDirectory has only a folder named as my app bundle ID. After the purchase, I see a zip file with a 32(hexa)digit for name and one named http_localhost_0.localstorage.

The zip file in the cacheDirectory indicates the hosted content has been downloaded; StoreKit then unzips this to a temporary directory, the location of which is passed to the plugin. The plugin recursively copies the contents of this temporary directory into the documentsDirectory. So if no files are present in the documentsDirectory, it's likely that StoreKit has not deployed them to the temporary folder and therefore the plugin has not found them in order to copy them to the documentsDirectory. In order for StoreKit to find them, they must be explicitly referenced in the project.pbxproj as well as placed within the XCode project folder. But as I've said, without seeing Objective-C debug output from the plugin, it's hard to know the exact cause. 

> Additionally, the structure of my in-app product is similar to demo (also Apple accepts it without any error), so I think that the problem is inside plugin and not in product.

You can see in the [XCode project file for the demo IAP project](https://github.com/dpa99c/cordova-plugin-purchase-demo-ios-hosted/blob/master/nonconsumablehosted1/nonconsumablehosted1.xcodeproj/project.pbxproj) that there is a PBXGroup entry for each content payload file. Check the project.pbxproj file for your In App Purchase project and confirm that the content files are referenced in PBXGroup entries.

I'd suggest downloading, configuring, building and running the [plugin's demo project](https://github.com/Fovea/cordova-plugin-purchase-demo) which demonstrates use of Apple Hosted content downloads using  the [demo IAP project](https://github.com/dpa99c/cordova-plugin-purchase-demo-ios-hosted).

As I said before, I'm successfully using the Apple Hosted content download functionality of this plugin in several production apps to sell In App Purchases to iOS users. There's no doubt the plugin functionality works (my weekly sales figures prove it), it just needs to be configured properly.

**Comment by dpa99c** [comment]
@gfragioud Are you still having problems or can this issue be closed?

**Comment by gfragioud** [comment]
Well I couldn' t understand why it remains in cacheDir and does not been copied to documentsDir, so I wrote a function for it and problem solved...

**Comment by j3k0** [comment]
Thanks @dpa99c for handling this. Would part of your answers be worth putting in a document?

**Comment by dpa99c** [comment]
Good idea @j3k0, I'll document the relevant parts when I have a minute and post the link here for reference

**Comment by dpa99c** [comment]
Created a [wiki page](https://github.com/j3k0/cordova-plugin-purchase/wiki/Apple-Hosted-Content) which explains Apple Hosted Content in a bit more detail.

**Comment by j3k0** [comment]
@dpa99c nice! :+1:
