### ISSUE TITLE
Product state.approved is never passed during a purchase, the last update is product.valid

### ISSUE THREAD

**Issue by aerialglasgow** [j3k0/cordova-plugin-purchase#328]
Great plugin! and have successfully configured the iOS plugin to vend around 20 IAPs. 

However within the Android app product.state == "approved" is never passed during a first purchase, after the BUY button is pressed in the test app I have running the last update is product.state == valid, then there are no further updates. The approved function is also never fired. But the transaction does take place and I am billed on the app store. 

However if the same product is then tried to be purchased again, product.state == "approved" is returned immediately. 

Could you suggest on what could be the problem? Thanks. 

function render() {

```
var product = store.get(buyProductId);

if (product.state == "approved") { 

    confirm(); // THIS FUNCTION FINISHES THE TRANSACTION IN THE APP 

} 
```

}

**Comment by Herb-sh** [comment]
I am struggling on the same issue but I am currently testing it on Android. First store.order() opens the product popup and after the purchase the "approved" event is not triggered instead an "updated" event is triggered. However It works if i click buy again, the product popup does not re-appear instead "approved" event is triggered directly and everything goes as expected.
I can not trigger store.order my self after the purchase because the updated event does not have authentic data.
How can we avoid a second click of the functionality? Thank you :)

**Comment by perttuim** [comment]
I have exactly the same problem. Ordering a product leads its state changing to "valid". When ordering again or calling product.finish() updated and owned callbacks are called and the state changes to "owned".
