### ISSUE TITLE
Is it mandatory to register products in advance?

### ISSUE THREAD

**Issue by enricodeleo** [j3k0/cordova-plugin-purchase#351]
Hi everyone,

I just started using this plugin but I have a doubt I hope someone could clarify:
I will have a lot of non consumable products and I'd like to make them browsable in various ways. As far as I can see from examples I would have to register all products in advance, but I think it will be more comfortable to lazy load products on demand. Is it possible? For example, can I open a category and load only the products related to that category, then switch to another one and do the same etc?

Thank you for your help!

**Comment by arielfaur** [comment]
I have the same problem. I have roughly ~1600 non-consumables. I have tried lazy loading products calling ```store.register``` after the initial ```store.refresh``` but it won't work. In the end I had to manage my products as a generic consumable that can be configured. Not the ideal scenario but the only way I could make it work. I just hope my app isn't rejected because of that!

**Comment by enricodeleo** [comment]
@arielfaur thank you for your feedback! As far as you know, how is usually managed this scenario on pure native apps? (for me is the first time I have to deal with IAP). Is it a limit of this plugin or does native storekit require such an approach?

**Comment by arielfaur** [comment]
I think it is related to this plugin. It has been mentioned here too #333.
They've done a great job with this plugin. Only thing missing is the ability to handle multiple non-consumables on demand. Let's hope for a fix soon :)

**Comment by enricodeleo** [comment]
@arielfaur yes, I see it is a great project indeed! I hope for the same fix as well!

**Comment by tehmaestro** [comment]
Hi. I had the same problem as you guys. Check out the last two commits on my fork https://github.com/tehmaestro/cordova-plugin-purchase/commits/master .

  I've created a `store.load()` function, which gets all store products that are not yet loaded, and retrieves data about them from Google. Also, I update the Inventory in Android, so it stays up-to-date, by adding the new products to the current Inventory. I had to make `addSkuDetails` function in `Inventory` class public in order to do this.

  Anyway, so what this allows me to do is:
  ```
    // register two products
    store.register({id: 'x', alias: 'x'});
    store.register({id: 'y', alias: 'y'});

    // call refresh, which initializes the plugin basically
   store.refresh();

    // at a later time, maybe you want to register new products
    store.register({id: 'a', alias: 'a'});
    store.register({id: 'b', alias: 'b'});

    // now, you can call load, in order to load the newly registered products
    store.load();

   // now, you can get data about product 'a'
    store.get('a');  // will return an object with title, price, etc ..
  ```

  Please note that when calling load, only the new products will be queried from Google. This is mostly what we want in order to make it faster.
  
  This is mostly an example of how it could be done. I'm not a Java developer myself, maybe somebody with more experience can take this further and/or make it better.

**Comment by arielfaur** [comment]
@tehmaestro Fantastic work! I just tried it on Android 4.1 and Android 6. Does it work on iOS too? Haven't had the chance to try yet.
I had 1000+ non consumables and I had given up on it. You saved me!  
I think you should seriously submit a pull request to merge this into the master. I am sure there are tons of other developers having the same problem. 
Thank you again :+1:

**Comment by AbuHani** [comment]
@tehmaestro Wow thank you !.

How to fix this issue on IOS ? is there a solution ?

**Comment by charlierz** [comment]
Any new on how to solve this for iOS?

**Comment by Luro91** [comment]
+1 It would be great if someone can implement this behaviour for iOS.
We are also loading products at a later point in time when we want to offer a promotion to a user.

**Comment by j3k0** [comment]
Maybe there are some people here willing to crowdfund this feature?

**Comment by danieldanielecki** [comment]
Added in-depth findings of apps using this purchase plugin in [#issue333 (comment)](https://github.com/j3k0/cordova-plugin-purchase/issues/333#issuecomment-533806270).
