### ISSUE TITLE
Do products have to be canPurchase: true?

### ISSUE THREAD

**Issue by rcwoodall** [j3k0/cordova-plugin-purchase#354]
Cool plugin! Not able to get it working. Itunes Connect is saying: "Your first In-App Purchase must be submitted with a new app version. Once your binary has been uploaded and your first In-App Purchase has been submitted for review, additional In-App Purchases can be submitted using the table below."

However, the documentation for this plugin says: "Important: Don't forget to add a screenshot and to set the product to cleared for sale."

How can we test ordering if the product is not cleared for sale? Do I really have to upload an entire binary before I can code functionality for an IAP?

I'm able to store.get() the product but everything is null:
{"id":"com.removed","alias":"unlimited","type":"non consumable","state":"registered","title":null,"description":null,"price":null,"currency":null,"loaded":false,"canPurchase":false,"owned":false,"downloading":false,"downloaded":false,"transaction":null}

There's no error when I do a store.order() and nothing happens. The return object is just a blank {} object.  I tried attaching your custom method to the store.error event but it's not throwing anything. I'm assuming firing off store.order will bring up some sort of icloud login dialogue, correct? Do I just have to wing this and not test anything?

I'm signed out of itunes, running on a real iphone connected to xcode. I've tried running it several ways (debug, profile, etc...). Anything I'm missing?

**Comment by Createstandard** [comment]
I was able to get a little further this time and am now experiencing this: https://github.com/j3k0/cordova-plugin-purchase/issues/22 load error on purchase. So I guess this means I have to submit a new app version and binary with the IAP before I can test?

**Comment by matthieu-D** [comment]
Hi,
I have the same logs : 
{"id":"com.removed","alias":"unlimited","type":"non consumable","state":"registered","title":null,"description":null,"price":null,"currency":null,"loaded":false,"canPurchase":false,"owned":false,"downloading":false,"downloaded":false,"transaction":null}
Did you submit your app in order to submit your products or did you succeed testing it in without submitting anything?
Was it a programming mistake?

**Comment by Createstandard** [comment]
@matthieu-D I don't know either. I coded the IAP feature in my app and then I submitted a new version to Apple but because I couldn't test the products, I commented out the IAP functionality. This was just so I could get the things approved. However, Apple rejected my update because the IAP functionality wasn't there! So I don't know how this is supposed to work. I told the Apple review team that the Itunes Connect UI says we have to submit a new binary for the first IAP and that I didn't understand. Their response was basically "fuck you that's not our problem talk to the Connect team".

**Comment by matthieu-D** [comment]
For me it was just the tax,bank informations to fill.

Enviado desde mi iPhone

**Comment by Createstandard** [comment]
Awesome. I also read there can be a 24 hour delay before when the data is correct on the sandbox api and I don't think I tested it later. So, I'm going to jump back in on this in a few weeks.

**Comment by kierandesmond** [comment]
Hey all, what was the result? Did you have to put the app in for review before you could test the feature fully?
