### ISSUE TITLE
Subscriptions validate

### ISSUE THREAD

**Issue by okhansen** [j3k0/cordova-plugin-purchase#366]
I have created an app with in app purchase and I'm able to buy subscriptions (Monthly). My problem, if it is a problem, is that every time I start my App, the App is validating all my subscriptions. I'm validating against my own server, validation is working, but is it correct that purchase plugin is testing all the subscriptions every time, both expired and active. 
As I'm testing with sandbox, the subscription is renewed every 15 minutes, so I got really many subscriptions to validate.
Any one that can explain how it works with subscriptions?

Thanks

**Comment by Pigsnuck** [comment]
Hi Okhansen,

Did you get any further with this?  I have a similar issue.  Basically, my subscriptions never expire.  On the server, I only validate that the status=0 and that the bundle_id matches my app.  I expect the plugin to detect the expired purchase.  Is this incorrect?

If so, then how do I return the correct response?  I mean, there are multiple transactions in the receipt, and some might be valid and others expired.  What should I return in this case?

**Comment by dirkpostma** [comment]
+1

**Comment by Pigsnuck** [comment]
OK, I can update this thread for anyone who is interested.

The plugin does NOT expire a subscription, upon app startup it relies on the server to parse the certificate and detect that it has expired (incidentally, it should also check the certificate is valid with Apple).  The problem is, if a hacker installs a valid certificate from a valid purchase in a pirated version and blocks access to your server API, the certificate will never expire (because the server never returns an INVALID_CERTIFICATE response).  

To avoid this issue, I implemented an extra piece of code which automatically deletes the certificate from the local storage if it detects the server has not been contacted for more than 10 days, and then calls restore(), which forces the user to enter their iTunes password and get the certificate from the App Store.  Of course, if it's a valid user the certificate is returned, and if not, then the subscription is not enabled.

**Comment by JefferE** [comment]
@Pigsnuck 

> To avoid this issue, I implemented an extra piece of code which automatically deletes the certificate from the local storage if it detects the server has not been contacted for more than 10 days, and then calls restore(), which forces the user to enter their iTunes password and get the certificate from the App Store. Of course, if it's a valid user the certificate is returned, and if not, then the subscription is not enabled.>

Any chance you'd be willing to share that code? (if you are still even a member of this community)
