### ISSUE TITLE
purchase flow confuse

### ISSUE THREAD

**Issue by mike623** [j3k0/cordova-plugin-purchase#416]
I saw the doc recommended "unlock feature" on approved callback but why not in finished callback ?

**Comment by j3k0** [comment]
That's to prevent a customer to have been debited before you effectively delivered the feature.

1. user requests purchasing stuff
2. you get authorization to debit from the bank (`approved` or `refused`)
3. you deliver the stuff
4. you finalize the transaction, user gets debited.

If the app crashes any moment between 2 and 4, an opportunity to deliver and finalize the pending order will be given at every app start, without penalty for you or your user.

If you finalize before delivering, but app crashes between "finalize" and "delivery", there won't be a pending order. The user paid, but doesn't have access to what he paid for.

That's why.

**Comment by mike623** [comment]
thanks for response! Here is few use case I concerned on ios:

most serious question is , can the vendor receive  payment  after approved call but never finish ?

I got some use case all from iOS

1. user approved -> delivered feature -> crash -> never login back to finish transaction -> vendor never   finalize the transaction ?

2 user click "buy" -> never got "you have purchased popup"

3 enabled auto finish ->  approved & auto finished -> no need call product.finish()? (i.e I skip verify step)

thx for help again

**Comment by j3k0** [comment]
1. Indeed if the user never ever launch the app again, transaction wont' be finalized: but the user isn't using the feature anyway...

3. auto-finish &rArr; no need to call product.finish, it's done for you (with the risk exposed before if app crash, but for convenience some people live with that)

**Comment by mike623** [comment]
How about just cancel the login popup when the store want to finish transaction?
I found it is hard to restrict user becoz they just press cancel to login popup and still enjoy the feature... And I have no way to  alert them "oh, your transaction not finish yet! please login to finish before use" but I can achieve it  on
`store.when('product').finished`
That's why I confuse that why I dont put on finish callback

**Comment by junioredmar** [comment]
I am having the same concern here. 

The case is that as soon as I receive the 'approved' state, the system unlock the feature for the user. But this feature can be also used in the current website (not only app).
If the user never opens the app again, he still can use the website features, and I never earn a cent.
