### ISSUE TITLE
iOS: Refresh on restore starts without wait for password

### ISSUE THREAD

**Issue by gfragioud** [j3k0/cordova-plugin-purchase#441]
When "restore purchases" is clicked, store.refresh() is called. (for second time)
Then a popup shows up and asks for appleID password but restoration starts without wait for user input.

I think that it should wait for password, or start without even asks for password...

Am I doing anything wrong or it' s a bug?

**Comment by rossi256** [comment]
I believe this is the same as i just posted in #439 ?

I am having big trouble restoring purchases - app went public now and i have some people not able to restore, some restoring only part of their old purchases and some not able to restore... probably this has something to do with it...

**Comment by gfragioud** [comment]
Any update on this would be really appreciated!

**Comment by j3k0** [comment]
A bug is possible. If you have the time to learn a bit more about what is happening this would be helpful.

**Comment by rossi256** [comment]
I would love to provide more info - i am not a real professional though - if someone points me in the right direction - what to check for, where, let me know... i'd also love to have a fix for this cause I believe it makes the restoring of old purchases in our new app not reliable.

**Comment by j3k0** [comment]
This would require some javascript debugging to understand what causes the refresh to be handled and why the password happens after that... If by "not a real professional" you mean "not a programer" this can be complicated, but if you're a programer that's an opportunity to learn something ;-)

I would start by downloading the git repo of the plugin, install the plugin in your project from the local directory where you downloaded the repo, then play with it to understand how it work...

If you feel like jumping in, I'm here to help.

**Comment by rossi256** [comment]
Sorry @j3k0 saw that just now.
I have only quickly looked into this and i am not enough of a programmer and i don't have enough time to really get into this...sorry... hope someone can track this down and fix it - i somehow believe many unsuccessful restore attempts of my app's users are cause of this...

**Comment by AustP** [comment]
I'm also getting this issue and I've done some digging around.

From Apple's [Restoring Purchased Products guidelines](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Restoring.html):

> Restoring purchases prompts for the user’s App Store credentials, which interrupts the flow of your app: because of this, don’t automatically restore purchases, especially not every time your app is launched.
> 
> In most cases, all your app needs to do is refresh its receipt and deliver the products in its receipt.

When `store.refresh()` is called for a second time, it ends up calling `storekit.restore()` and `storekit.refreshReceipts()`. You can see this here: [src/js/platforms/ios-adapter.js#L424](
https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/platforms/ios-adapter.js#L424)

`storekit.restore()` always pops open a credential modal. `storekit.refreshReceipts()` will pop open a credential modal if the user is not signed in.

So if a user is signed in, `restore()` will open the credential modal but `refreshReceipts()` will "restore" the purchases anyways.

In the instances where the user is not signed in, `restore()` will open the credential modal and then `refreshReceipts()` will open the credential modal which closes the restore modal and triggers the restore failure callback.

I was gonna try to make a few builds to test this theory by commenting out one or the other of these function calls but ran into a snag with my app. I'm gonna try to get those builds tomorrow.

**Comment by AustP** [comment]
It looks like PR #376 adds a autoRestore feature. That might be the best way to solve this issue.

**Comment by AustP** [comment]
I got some testing and here are my results. I had 3 different plugin builds that I was testing from.

control: This build is just the standard plugin build, no changes.
refreshReceipts(): This build commented out `restore()` and only ran `refreshReceipts()`.
```
//storekit.restore();
storekit.refreshReceipts(...);
```
restore(): This build only ran `restore()` and commented out `refreshReceipts()`.
```
storekit.restore();
/*storekit.refreshReceipts(...);*/
```

(The changes were at [src/js/platforms/ios-adapter.js#L424](https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/js/platforms/ios-adapter.js#L424))

I tested each build with 2 setups. Before I describe the setups, I need to talk about iOS accounts. On your iDevice, you can be logged in with 2 different accounts at the same time. The first is an iCloud account and the second is a store account. They can be the same account or they can be different accounts. The store account is the one that is tied to test users.

1 Account: No iCloud account logged in. A store account logged in. The store account was my test user account.
2 Accounts: An iCloud account logged in. A store account logged in. (Test users can't have iCloud accounts so the iCloud account was my real iCloud account and the store account was my test user account.)

Here are the results:

| Build - Setup | Restored? | Did modal show? |
| --- | --- | --- |
| **control - 1 Account** | **Yes** | **No** |
| control - 2 Accounts | **Yes** | Yes |
| refreshReceipts() - 1 Account | No | **No** |
| refreshReceipts() - 2 Accounts | No | Yes |
| **restore() - 1 Account** | **Yes** | **No** |
| **restore() - 2 Accounts** | **Yes** | **No** |

We are looking for builds and setups that restored and did not show a modal (bolded in the list).

Now from this list of results we can learn a few things about this issue. The control build (normal plugin code) doesn't have this issue (Restoring without waiting for credential modal) when logged in with only 1 account. Because a test user can't have an iCloud account, I assume that if the 2 accounts are the same, that the modal **would not** show. I couldn't test this though. But it is my assumption that this issue really only shows up when testing, but not in production because of this.

However, we can see that the `restore()` build worked perfectly in both scenarios. The only hesitancy I have is from the Apple guidelines that I quoted yesterday that says we should be calling refresh receipts rather than restore. But looking at the results only calling refresh receipts didn't work in either setup. One even popped open the modal but still didn't restore purchases.

So because this issue probably won't show up in production (unless the user actually does have a different iCloud account than their iTunes store account), it's probably fine to mark this as a non-issue. However, skipping the call to `refreshReceipts()` and only calling `restore()` gave me perfect results in my testing so we might want to update the code to always do that anyways.

@j3k0 @Dexus thoughts?

**Comment by Dexus** [comment]
The problem that i see is you need to restore on other devices to call `refreshReceipts()` so it's a importend call. So i don't know yet if it will good to skip it, or with what for a check we should decide to call it.

But when we would do it correct, we should implement if not already done, the option to call it on user request. Cause that would be the best approche, I think.
