### ISSUE TITLE
Cannot connect to iTunes Store 6777010 with perfect internet connection

### ISSUE THREAD

**Issue by heaven** [j3k0/cordova-plugin-purchase#446]
I have a stable connection and every time I request a purchase it asks me for the password, I enter it using touch id 3 times in a row and then see this error in console.

Entering password manually often fixes the issue and touch id also starts to work for next purchases. After some time this happens again.

**Comment by j3k0** [comment]
Are you using a Test User account when in development?

Please check out this list:
https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO#test-ios-applications

**Comment by heaven** [comment]
This happens with both test and my own itunes accounts. I simply can't purchase, it asks me 3 times for my touch id and then fails and the mentioned error appears in the logs. Other people in our team can also confirm this issue.

**Comment by j3k0** [comment]
1. Close the app
2. Make sure you have logged out of iTunes from your phone settings.
3. Open the app
4. Make a purchase, logging with a Test Account from within the app.

Notes:
 * if you ever try to make a purchase with a production account while doing development, the thing may stop working until you reboot the phone
 * if you ever try to make a non-sandbox purchase (like when browsing the AppStore) whenever you're logged in with a Test User, the account can be silently disabled by Apple...

**Comment by j3k0** [comment]
This kind of ticks to me, because TouchID cannot work with a Test User, so you're probably trying something wrong... except if you are describe something on the version you downloaded from the App Store.

The plugins documentation explains how you should test on iOS.

**Comment by JWesorick** [comment]
I am having this same issue. (it asks me 3 times for my touch id and then fails and the mentioned error)

**Comment by anchann** [comment]
For what it's worth, the problem that I had was that the in-app purchase I was trying to test was stuck in "missing metadata" state, with the only localization in the list having the yellow dot next to it. It turned out that the error was indicated incorrectly, and uploading the screenshot for in-app purchase review switched the state of the in-app purchase to "ready to submit". After that, the purchase succeeds on device in the OS-side flow, though for some reason the `invalid` callback is called on the product... off to debug that now.
