### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by jdnichollsc** [j3k0/cordova-plugin-purchase#488]
Hi guys!

One question... Can I use In-App Purchases for donations on Android and iOS?

Regards, Nicholls

**Comment by EerikKivistik** [comment]
You shouldn't use the name "donations", it can cause problems, since there are regulations that may apply. What you could do, is have consumable items in the store, that are "tips". So for Android you would add a regular in-app purchasable item, and consume it after it has been purchased. On iOS you can just register a consumable item and purchase it.

**Comment by jdnichollsc** [comment]
Thanks for the tips, for example to remove Ads :100:
