### ISSUE TITLE
owner status of item seems to get reportet 4 times

### ISSUE THREAD

**Issue by ChristianGrieger** [j3k0/cordova-plugin-purchase#507]
I would love to fire or not fire a function on startup of the app.

`store.when("full version").updated(function (product) {
        document.getElementById("in-app_purchase_list").style.display = product.owned ? "none" : "block";
        if(product.owned){
            paidVersion = 1;
        }else{
            paidVersion = 0;
        }
    });`

I check the product owner in the update function but i have the problem that it get fired 4 times.
So it would happen that it fires the function even if the project is owned because the reply is:

not owner, not owned, owned, owned

How can i get sure that it only reports it one time with the right result?
Right now i added a 5 second delay to the function that needs to get fired for the ads to get the right value paid or not paid version from the store info but i think this cant be the solution :/

**Comment by j3k0** [comment]
`updated` is called each time there's an update to the product.

When app starts it's gonna load the product definitions, so it goes from unknown, to registered, to loaded. Owned products will then go to approved and finally owned.

Each of this step, an `update` is triggered. Last call is the final value.

You can also use `.owned()` instead of `.updated()` if you only want a function to be called when product enters the `owned` state.

**Comment by ChristianGrieger** [comment]
The problem is that i need a not owned function. So app starts and need to add some ads if the product is not owned. So when it first checks it would tell not owned after the check it tells owned but then its to late because the ads are already displayed :/

**Comment by j3k0** [comment]
I think you can check the status of ownership when store's `ready` callback fires. Not 100% sure about that (it's been a while).

https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storereadycallback

**Comment by ChristianGrieger** [comment]
I will give it a try. Thanks
