### ISSUE TITLE
Unable to generate receipt using sandbox tester account

### ISSUE THREAD

**Issue by lovey92** [j3k0/cordova-plugin-purchase#523]
Hi Everyone,

I have integrate this plugin in my app. I have created product as auto renewable product and in app I am registering product as type: store.PAID_SUBSCRIPTION.

I am able to make payment successful using sandbox tester account but not able to generate its receipt.

Can anyone please let me know how can we generate receipt using this plugin.I have also use given below code but no luck-

store.validator = function(product, callback) { }

Any help will be appreciated.

**Comment by piin** [comment]
I have the same problem, I want to implement "subscriptions" and I don't know how to create my own receipt validation, I know I have to create a path in my API but what should I return or whats the function to the validator, Can anyone help me.

**Comment by j3k0** [comment]
Hello, you can try out https://billing.fovea.cc -- it's still in beta (and free while so), it will do the receipt validation for you.

**Comment by piin** [comment]
Thanks @j3k0, but I want to create my own receipt validation, I've already have my API but I need more details or a tutorial, I don't know what should I return or whats the validator function?

**Comment by ithav** [comment]
@piin 
please try this:
store.validator = function(product, callback) { 
   // verify() call (see below) should result in having product.transaction.appStoreReceipt
  // that is your receipt with which you should post to appStore
}

store.when(product.id).approved(function(p) {
       p.verify();  // this calls the validator function with enriched transaction data on product
});

**Comment by ekntrtmz** [comment]
@j3k0 I tried to registert at https://billing.fovea.cc and did only get a "Help us by Sharing" Email. 
I have implemented the plugin and try to use subscription. As I have found out it only works, when verification is used. Since I am not able to write my own verification server script I need to use your service. Unfortunately I can not access to that service.

So please help me out: How to verify these subscriptions, so that their status automatically sets back to Valid from Owned, when they are expired.

Thanks!
