### ISSUE TITLE
Allowed to strip away app name from title?

### ISSUE THREAD

**Issue by remisture** [j3k0/cordova-plugin-purchase#544]
Hi,

On Android, all my product titles are on this format: "Product xxx (App name)". Since all my users know the name of my app, are there any reasons why I can't strip away that part in my UI?

**Comment by Jay031** [comment]
I saw on stackoverflow that it's how Google works, but it's a bit outdated: http://stackoverflow.com/questions/16657310/how-can-i-avoid-app-names-in-inapp-item-titles-returned-from-google-play-getskud

I don't have this issue in my app, but I'm using Auto Renewable Subscriptions, so that might be the difference. So your In App Purchase title is: "Product xxx" and when you receive it in your app you get "Product xxx (App name)"?
You could, worst-case-scenario, strip this text with some filter, but that would not be the most elegant way ofcourse..

**Comment by remisture** [comment]
> So your In App Purchase title is: "Product xxx" and when you receive it in your app you get "Product xxx (App name)"?

Correct.

**Comment by stevecohenfr** [comment]
I got the same issue "Product xxx (App name)"

**Comment by j3k0** [comment]
The cordova plugin sets the product title as it's returned by Google. If you want to dig into that, it has to be with the [android developer support](https://developer.android.com/support).

I know it's a bit ugly, just don't use parenthesis in your product's title then trim everything after (and including) the first `(` when you're displaying it.
