### ISSUE TITLE
How reliable is this plugin?

### ISSUE THREAD

**Issue by armandn** [j3k0/cordova-plugin-purchase#596]
First, I'm sorry if this is not a real issue, but I known't know of a forum I can discuss this on.

I have a Cordova app and I'd like to add in-app purchases to it, but frankly I'm scared. I see quite a number of issues here; I just don't know how widespread they are... The thing is, if a user makes a purchase and something goes wrong, they will definitely complain and leave a bad review...

Can anyone tell me how reliable this is for Android and iOS? Thank you.

**Comment by Dexus** [comment]
Hi, this plugin is the most used plugin for Cordova in terms of payment.

There are so many issues because no one reads the documentation and because there are still some old bugs and issues that were never closed.

I personally have so far no problems with this plugin had, whereby currently only a bug is thereby possibly interfering could. This is also the only bug currently tagged.

This is open source, so the support is also hard, since we all have little time ... So if there are questions, ask, and it will give someone answers, if he can and wants.

greeting

**Comment by ultisoftmeta** [comment]
I am using this plugin for iOS and testing via TestFlight (sandbox environment). Problem is that sometimes the purchase goes smooth and sometimes my app crashes while loading storekit. I will realy appreciate your help in giving any pointers/hints. Thank you so much for your help.

Technical Details are below:
https://github.com/j3k0/cordova-plugin-purchase/issues/603

**Comment by Dexus** [comment]
Hello I would say its a outdated tutorial... 
please look into the linked examples  of this repo... thank you!

Von meinem iPhone gesendet
