### ISSUE TITLE
Handling of unfinished consumable transactions on iOS

### ISSUE THREAD

**Issue by mehmetkoc182** [j3k0/cordova-plugin-purchase#620]
Thanks for this awesome plugin! We've been using it for our android app for quite some time and it worked great for over 6 months.

However, we're having an issue with IOS consumable purchases where if the initial purchase fails for any reason, we can't do any more purchases of that consumable after. The IOS throws the "you already own this product, click here to restore" button. And that button doesn't send any event back.

There were a few similar issues here that looks resolved, although these solutions didn't work for us:
https://github.com/j3k0/cordova-plugin-purchase/issues/448
https://github.com/j3k0/cordova-plugin-purchase/issues/94

And there is a stackoverflow thread that I think explains the state I'm in and why. They suggest a fix in the native IOS code but I don't know enough objective C to understand and/or compare the source code of the plugin with.
https://stackoverflow.com/questions/29244903/sandbox-trying-to-restore-consumable-iap

This is the last hurdle we have until we can submit our app to the app store.
Any help will be greatly appreciated.

Thanks!
Mehmet

**Comment by tt-rkj** [comment]
I've been having the same problem with unfinished consumable transactions, and I believe it might be because the transaction observer is added too late for it to pick up unfinished transactions.

From the apple programming guide for in app purchases: (emphasis mine)
/https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/DeliverProduct.html#//apple_ref/doc/uid/TP40008267-CH5-SW4

> **Register a transaction queue observer when your app is launched**, as shown in Listing 5-1. Make sure that the observer is ready to handle a transaction at any time, not just after you add a transaction to the queue. For example, consider the case of a user buying something in your app right before going into a tunnel. Your app isn’t able to deliver the purchased content because there’s no network connection. **The next time your app is launched, StoreKit calls your transaction queue observer again and delivers the purchased content at that time. Similarly, if your app fails to mark a transaction as finished, StoreKit calls the observer every time your app is launched until the transaction is properly finished**.

My problem is that this plugins transaction observer is NOT called, even though i receive the "you already own this product, it has been restored" message when trying to purchase the unfinished product again.

Apple recommends the following code:
```
- (BOOL)application:(UIApplication *)application

didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
/* ... */
 
[[SKPaymentQueue defaultQueue] addTransactionObserver:observer];
}
```

But i see that the observer is only added in the setup function at https://github.com/j3k0/cordova-plugin-purchase/blob/master/src/ios/InAppPurchase.m#L298

I have also noticed that when I'm running the FirebaseAnalytics plugin, there are messages about duplicate purchases in the debug log on xcode when the app starts up. This leads me to believe that the unfinished transactions ARE being sent to observers, but just does not reach this plugins observer.

I'm going to try and experiment with a solution where the observer is added as soon as possible in the app startup phase, but would be happy to hear any feedback on this issue, since I don't have experience with native iOS applications or cordova plugins for that matter :)

**Comment by j3k0** [comment]
This is the commit 6a779a76007e1cbed167389b7048423a7d8413a4 (branch contains some cleanup that make it bigger than required)

**Comment by tt-rkj** [comment]
This is great! I will try it out right away and let you know how it goes

**Comment by tt-rkj** [comment]
Beautiful, it just works! I had two test accounts with unfinished transactions from previous days of troubleshooting this exact problem, and they were both correctly updated and finished as soon as the store was initialized. I didn't have to change a line of code.

Man you have no idea how much i have been pulling my hair out about this, and dreading trying to figure out a fix by myself - you just made my weekend :)

Let me know if I can help out in some small way, or maybe donate towards this plugins development, since I don't have that much spare time right now.

**Comment by mehmetkoc182** [comment]
I still don't get any call backs from that "restore my purchase" button. 
When I hit the restore button, the product get initiated but it never gets set to the approved state when we do get approved by apple servers.

However when I restart the app it runs a store refresh and finishes those unfinished purchases, which frees up the product at least but is there a way we can make the actual restoring work?
