### ISSUE TITLE
Example of validator service?

### ISSUE THREAD

**Issue by remisture** [j3k0/cordova-plugin-purchase#714]
Has anyone seen a working example of how to make your own validator service using Node or PHP or whatever?

**Comment by ShimshonMarketing66** [comment]
+1

**Comment by j3k0** [comment]
Did you consider using a hosted solution? (https://billing.fovea.cc).

**Comment by znegva** [comment]
I am also interested in a working example, esp. as it is mandatory to use a validation service if you want to use subscriptions on iOS reasonably (see [here](https://github.com/j3k0/cordova-plugin-purchase/blob/1599df9a4b199cc5057cdb3c61ac181ba6bcc709/www/store-ios.js#L261))

**Comment by paulstelzer** [comment]
If you want to use nodejs, please see this -> https://github.com/voltrue2/in-app-purchase

**Comment by lfreneda** [comment]
@paulstelzer do you implemented a working sample?

**Comment by paulstelzer** [comment]
@lfreneda I created my own purchase validation service based on nodejs without third party packages just for subscriptions and yes, that's working fine.

But you don't need to write it yourself because there are already packages for it (like I mentioned in https://github.com/j3k0/cordova-plugin-purchase/issues/714#issuecomment-441557617)

**Comment by lfreneda** [comment]
@paulstelzer thanks, I will try it out :+1:
