### ISSUE TITLE
[ANDROID] Expected Flow for subscription purchase and init app

### ISSUE THREAD

**Issue by lfreneda** [j3k0/cordova-plugin-purchase#777]
Hello there.

Just read about in-app purchase flow in others issues, but this question still confusing to me.

The approved event is triggering every time I start my app, is this an expected behavior? Should I validate the transaction in every app start?

I'm responsible for checking subscriptions expiration time?

Is there any sequence diagram to illustrate better this cycle of events?

Thanks

**Comment by j3k0** [comment]
>approved event is triggering every time I start my app

It is an expected behaviour. You should validate the transaction at every app start : it might have been cancelled or refunded.

>checking subscriptions expiration time

The server should do it, you have to integrate with Apple/Google APIs to get the transaction status and expiry date. Are you using your own validator?

**Comment by rafaellop** [comment]
Update: the above was probably due to the Google Play Services. I restarted the device and it does remember the owned now and reports it at the init and `store.refresh();` However the other issue is still present. There's no event if the subscription is cancelled by the user. I don't receive neither `expired` or any other event that could be helpful in that case.

**Comment by j3k0** [comment]
Cancelling a subscription won't trigger an event in real-time (as the native billing SDK don't notify the app in any ways). There's a server side "real-time notifications" API that you can implement if you need just-in-time subscription status.

The normal flow is that the subscription status will be checked next time the app is started. If your receipt validator is implemented properly, it will detect that the transaction has been cancelled and return the appropriate error code (so the client-app will know the user isn't subscribed anymore).

A good enhancement to the plugin's API would be to add a method to trigger a revalidation, so the app can forcefully check the subscription status before (for example) downloading some new content. Such API isn't implemented at the moment. I'll add it to the backlog.

**Comment by dominic-simplan** [comment]
@j3k0 So calling store.refresh() periodically is not a good way to check if the subscriptions are still valid?

**Comment by j3k0** [comment]
@dominic-simplan Calling store.refresh() regularly can be a solution, on iOS this will generally open a dialog for the user to enter his/her password.

However, I don't think there's a real problem here. The default behavior is to refresh all statuses when the app starts, it is good enough since subscriptions are generally counted in days and not in hours/minutes. Apps don't stay backgrounded for hours, last time I checked, the average on iOS was about 10 minutes. You're pretty much guaranteed to refresh the status at least once every day.

**Comment by dominic-simplan** [comment]
@j3k0 okay, thanks! I saw the iOS dialog but I wasn't sure how it exactly works because of  [this comment](https://github.com/j3k0/cordova-plugin-purchase/issues/441#issuecomment-339436360), which says that the popup is only shown if two different accounts are used for iCloud and the AppStore.

Anyway, if the iOS apps are started anew at last once a day, this is fine for me. 
I think Android also removes the background apps regularly, however there is an option to exclude apps from the battery optimization. I don't know how this would affect the background cleaning.
Only Windows, on the other side, you could leave the app open indefinitely if you only send your PC to sleep.

So probably I'll add a check for Android and UWP to call the refresh() method if it hasn't been called in the last 24 hours or so.
An API for revalidation (as you've mentioned above) which can also be used on iOS would probably be nice in the long run :-)

**Comment by j3k0** [comment]
>Only Windows, on the other side, you could leave the app open 
>indefinitely if you only send your PC to sleep.

Good point, didn't think of that.

I guess the best course of action would be that the plugin decide when 
to do a revalidation (so it's not something developer have to worry 
about, they just have to know that it's handled).

It's actually a very simple change since `refresh()` on Android and 
Windows do not trigger password popups. I can simply `setInterval` this 
call every 24 hours. On iOS, nothing will be done.

I'll make a PR right away. Let me know if you think there's a better 
approach.
