### ISSUE TITLE
[IOS & ANDROID] Purchase Authenticity Validation

### ISSUE THREAD

**Issue by bshafiee** [j3k0/cordova-plugin-purchase#793]
Hi there, 

 Thanks for the amazing work. I have a question about a threat model that I can't figure out. Let's say, someone purchases a simple non-subscription (1-time non-consumable product) so then this is called:
```
    this.store.when("BestProductID").approved((product: IAPProduct) => {
            myApp.StorePurchaseOnServerAndUnlock(BestProductID)//includes storing on app-server the purchase record
            product.finish();
        })
...
```
and I can't figure out why an attacker can't just call,`myApp.StorePurchaseOnServerAndUnlock(BestProductID)` directly? So that he/she wouldn't need to pay an own the `BestProduct`? What's the way for my server to understand that that transaction happened for real. Please, note I am not talking about subscriptions here. I feel like there should be some transaction ID that my server can send to google and apple and ask if that's valid before storing the purchase record. 

I'll be really thankful if someone can clarify and provide some example of how to handle this. 

Thanks,

**Comment by j3k0** [comment]
Hi @bshafiee,

The proper way to handle this is to do server-side receipt validation. Together with your `Unlock` call, you can send the transaction details to your server, then check from the server what's the status of the transaction (it might also be valid but cancelled).

The server will validate the receipts with Google/Apple's own APIs, then perform regular update of the status (to figure out cancellation, renewal for subscriptions and other subtleties to prevent fraud) in order to to keep the status of a user up-to-date.

If you want a quick and tested solution you can use [Fovea's receipt validation service](https://billing.fovea.cc/). It's fully integrated with this plugin ([see doc](https://billing-dashboard.fovea.cc/setup/cordova)). You can then request the status of Apple and Google users with a single API: https://billing.fovea.cc/customers-api/ - we do the heavy lifting.

**Comment by bshafiee** [comment]
Hi @j3k0, 

Thank you so much for your answer. It makes sense and clarifies things for me!
