### ISSUE TITLE
Which version is correct?

### ISSUE THREAD

**Issue by remisture** [j3k0/cordova-plugin-purchase#836]
[Ionic Native](https://ionicframework.com/docs/native/in-app-purchase-2) says `ionic cordova plugin add cc.fovea.cordova.purchase`, which maps to version `7.4.3`, while it here says `cordova plugin add cordova-plugin-purchase` (version 7.2.8). What is the correct version to use?

**Comment by j3k0** [comment]
For a while I'll maintain both IDs. `cordova-plugin-purchase` is the new official plugin ID. `cc.fovea.cordova.purchase` being the legacy ID, I might not update it for every new features (since I assume it's being used by existing apps or referenced in tutorials that don't make use of the new features)... Might not be a correct assumption though.
