### ISSUE TITLE
Get purchase response

### ISSUE THREAD

**Issue by Isuru-nibaya** [j3k0/cordova-plugin-purchase#844]
Hi after i press subscribed button in android phone and pop  up "payment successful" and i want to get purchase response in order to save in the back end . how can i get this done please help me .

// initaite purchase 
 store.order(mydata).then(function (data) {
            }).error(function () {
              
              
            });

**Comment by j3k0** [comment]
Hi @Isuru-nibaya 

First, you should handle `approved` events from a handler registered at startup. `store.order(mydata).then` only works if the purchase is initiated and completed in the same session, which isn't always the case, and doesn't handle subscription renewal. The general solution:

```js
store.when('subscription')
     .approved(p => p.verify())
     .verified(p => p.finish())
     .owned(p => console.log(`you now own ${p.alias}`))
     .expired(p => console.log(`subscription to ${p.alias} has expired`));
```

You need a receipt validator in order to prevent hacking and to get the full subscription data. On Android, some incomplete data is provided by the client API (but shouldn't be trusted). Inspect the product (`p`) after the `owned` event to see what's provided.

For integrating with Google Developer API, [Fovea.Billing](https://billing.fovea.cc) could do the heavy lifting for you server-side, let me know if you need assistance with that!

**Comment by Isuru-nibaya** [comment]
HI @j3k0  so sorry for interrupt you  I did as you said and i want to get latest transaction details of the current purchase currently i get transaction null and send back to the server in order to do server side validation.

**Comment by csabagasparik** [comment]
+1
(transaction: null)

**Comment by j3k0** [comment]
Can you provide more details: I've tested this (and I think many other devs) and it's a feature that works and have been working for a long time. What's your setup? (android version of your device) Any interesting logs in `logcat`?

**Comment by csabagasparik** [comment]
Hi!

@j3k0 thaks, it works for me!

@Isuru-nibaya for me it worked before. the issue headed up, when I upgraded form android 7 to 8. my plugin version was 7.4.0. just updated the plugin to 8.0.0 and everything is working fine now!

**Comment by j3k0** [comment]
@csabagasparik Good to hear! @Isuru-nibaya feel free to re-open if you still experience the issue with the latest version of the plugin.

**Comment by chathura-rightapps** [comment]
Hi I'm chathura. Currently I'm trying to use your plugin. Firstly I need to get the available products from the store. But I get undefined as the result. Can you help me if I have done it incorrectly.
Firstly what I did was add the plugin with the billing key for android.
