### ISSUE TITLE
Storekit.load does not work for second product IOS

### ISSUE THREAD

**Issue by CharnjeetIotasol** [j3k0/cordova-plugin-purchase#849]
# [IOS] 

### Expected behavior
Store.register second time does not load the product it mark the status to Register not Loaded.
### Observed behavior
It should be load the product
### Steps to reproduce

I am using the Ionic 4 application and I have a detail page of every product where I want to buy now button. When I have register product first time then It loads it from a store that is it price and marked status as valid and loaded:true and click on buy now then it working fine open the purchased popup

But when I have cancel the first product purchase and try to purchased second product and call the store.register then it does not load the product detail and product status is "Register" and loaded is false. So, when click on Buy now it does not work.

Can you please help me.

**Comment by Dexus** [comment]
@CharnjeetIotasol you need to register all products initial. you are not able to register products after initial `store.refresh();` call

**Comment by danieldanielecki** [comment]
@CharnjeetIotasol might be related with [issue#333](https://github.com/j3k0/cordova-plugin-purchase/issues/333), [issue#351](https://github.com/j3k0/cordova-plugin-purchase/issues/351). They have been closed due to inactivity, I summarised it recently in [issue#938](https://github.com/j3k0/cordova-plugin-purchase/issues/938). I gave an in-depth explanation about this (or at least very similar) issue in [#issue333 (comment)](https://github.com/j3k0/cordova-plugin-purchase/issues/333#issuecomment-533806270).
