### ISSUE TITLE
[ANDROID] Signature verification failed

### ISSUE THREAD

**Issue by ndevtag** [j3k0/cordova-plugin-purchase#866]
Hello, 
i have built a test application for making a subscription with this plugin using Ionic 4. I have released a closed alpha version of my app and can get additional product informations from my test product in Play Store. I can purchase the subscription, but after the payment is finished in Play Store i get an error.
I have already looked after the correct BILLING_KEY. Thats not the problem. I have no more idea, where the problem is. I hope i can get som advices here, what the problem might be. For additional informations, feel free to ask.

### system info
Windows 10
Cordova 8.0.0
Device: Android 8.0.0
Plugin Version: 8.1.0

### Expected behavior
Get Approved-Event with Data after Payment is finished

### Observed behavior
Get Error after payment is finished: 
"Purchase failed: Error purchasing: IaBResult: Siganture verification failed for sku nt.ag.test_purchase (response: 6777017:Error)"

**Comment by j3k0** [comment]
As far as I know, signature verification is linked with an incorrect `BILLING_KEY` (because that's what is being used to check it). So you were right to look in this direction. I've seen some people assuming the `BILLING_KEY` is the same for all apps, which it isn't (mentioning it just in case).

In case the setup didn't go properly, you can try uninstalling then reinstalling the plugin. Make sure you didn't add a space or something in the value for the billing key... It should start with `MIIB` and end with `DAQAB`.

In your `logcat` output you can also search for `Purchase data` and `Data signature` which should not be empty...

**Comment by ndevtag** [comment]
Deoending on other problem, mentioned in #898
