### ISSUE TITLE
[ANGULAR] Unknown provider: storeProvider <- store

### ISSUE THREAD

**Issue by Staarks** [j3k0/cordova-plugin-purchase#908]
I'm getting this error.

Error: [$injector:unpr] Unknown provider: storeProvider <- store <- SubscriptionController

My code looks like this:

```js
angular.module('app').controller('SubscriptionController', SubscriptionController);

function SubscriptionController($scope, store, StateService){

        const vm = this;
        activate();

        function activate(){
            console.log("Load carousel window.");

            //Register the products
            store.register([{
                id:    '1month_subscription',
                type:   store.PAID_SUBSCRIPTION,
            }]);

}
```

I already have the cordova-plugin in my config file.

```xml
<plugin name="cordova-plugin-purchase" spec="https://github.com/j3k0/cordova-plugin-purchase#master">
    <variable name="BILLING_KEY" value="MIIB" />
</plugin>
```

What am I missing? Why the store is not being recognised in my project?

**Comment by lalmanzar** [comment]
The store is a global window variable, you are adding it as a dependency on the subscription controller. This means angular is expecting to find some serviceProvider for "store".
Just remove it from the controller parms and use it as a globar variable. Or create a service that will return the globar store (this approach is better since you can unit test the controller by mocking the store):

```
angular.module('app').factory('store', function() {
  return store;
});
```
