### ISSUE TITLE
[ANDROID] Restoring cancelled subscription before expiry

### ISSUE THREAD

**Issue by 8bhsolutions** [j3k0/cordova-plugin-purchase#930]
I'm using latest version of the plugin.

I can't seem to find documentation (or figure out) on how to restore a cancelled subscription before expiry

Calling order() with the same sku results in a new purchaseToken being generated.

Based on android's offical documentation, restored subscriptions should have same purchaseToken.
https://developer.android.com/google/play/billing/billing_subscriptions#restore

Help would be appreciated.

**Comment by 8bhsolutions** [comment]
I've had no response.

Hoping this doesn't get closed.

**Comment by 8bhsolutions** [comment]
@j3k0

**Comment by nvahalik** [comment]
Note that the UI you are seeing here is something Android/Google Play provides. It's not something that you can do within the app or this plugin. It's functionality that is external. That is why you are not getting an answer to your question: because the plugin doesn't do this: Google Play's store does.

**Comment by j3k0** [comment]
Sorry, I let GitHub issues slip through. Thanks @nvahalik for answering this one. Indeed the plugin is just an interface to the native SDK. Indeed, after some time google doesn't consider "re-purchase" of the same subscription a "restored subscription" but a new purchase.

**Comment by 8bhsolutions** [comment]
@nvahalik  @j3k0 
Thanks guys for the clarification
