### ISSUE TITLE
[ANDROID] what happened to the billing key?

### ISSUE THREAD

**Issue by Gerarddus** [j3k0/cordova-plugin-purchase#972]
In version 10.0.1 the use of the billing-key parameter for Android has been removed. However, in the Android docs is says:

```https://developer.android.com/google/play/billing/billing_library_overview```

> Verify a purchase on a device
> If you cannot run your own server, you can still validate purchase details within your Android app.
> 
> To help ensure the integrity of the transaction information that is sent to your application, Google Play signs the JSON string that contains the response data for a purchase. Google Play uses the private key that is associated with your application in the Play Console to create this signature. The Play Console generates an RSA key pair for each application. You get this response JSON using the getOriginalJson() method within the Purchase class.
> 
> Note: To find the public key portion of this key pair, open your application's details in the Play Console, click Services & APIs, and review the field titled Your License Key for This Application.
> The Base64-encoded RSA public key that is generated by Google Play is in binary encoded, X.509 subjectPublicKeyInfo DER SEQUENCE format. It is the same public key that is used with Google Play licensing.
> 
> When your application receives this signed response, you can use the public key portion of your RSA key pair to verify the signature. By performing signature verification, you can detect any responses that have been tampered with or that have been spoofed.

So I was wondering what the reasoning is for removing this?

**Comment by Dexus** [comment]
The reason for this is, that your app is easy to decompile and includes those keys if they are not compiled. (No is html css and co are not compiled...) and also encrypted/obfuscated.

So you need a Server or you need a „browser extension“ That includes the security things what is difficult to do with a plug-in like this.

Von meinem iPhone gesendet

**Comment by Gerarddus** [comment]
Thanks for you answer. Yes, I know that the app is easy to decompile, but I'm using an encrypted version of the billingkey that I'm decrypting in java only (and that's why I'm using the proguard plugin as well). The use of a server is my next step (probably Fovea :) ). I think that using the billingkey in this way is still useful, especially since Google recommends this.

**Comment by Dexus** [comment]
Can you give me your app ID? I send you your key... 😇

Java is not really save against decompile. That’s why the most firms behind the apps do all the stuff that are important like payments on servers not on the app.

Think about it. A hacked app should never work because your api/backend should be check and compute some very needed functions.

Von meinem iPhone gesendet

**Comment by Gerarddus** [comment]
Lol ok ok ok.
But but but... So you're basically saying that all the stuff with the billingkey in the previous versions (<10.0.0) of this plugin was useless?

**Comment by Dexus** [comment]
I think @j3k0 can tell you more.

I can only tell you how I think and do my apps. I don’t like to see others release my app and work for free (hacked apps).

Von meinem iPhone gesendet

**Comment by Gerarddus** [comment]
Thanks for your comments!

**Comment by j3k0** [comment]
Sorry about lag in answering, just back from vacations!

When re-implementing the plugin I didn't add back the on-device signature validation on Android. The way it was implemented caused many issues with users when installing / uninstalling / upgrading the plugin, so I wanted to get rid of this problem.

The signature validation code is still there in `src/android/cc/fovea/Security.java` but needs to be plugged in. I'm considering making it optional and allowing the user to specify the billing key from javascript.

Like so:

```js
store.init({ androidBillingKey: "deadbeef", ... });
```

As explained by Dexus, having the Billing Key in clear in your app makes it super easy to hack (automated hacking tool can search & replace the value), yet minimal security might still be better than no security at all. Anyone can implement custom obfuscation...

```js
const A = "android";
const B = "Billing";
const K = "Key";
const config = {};
c[A + B + K] = prefix();
c[A + B + K] += suffix();
store.init(c);
```

However, the best is by far to have server side validation, since [Fovea](https://billing.fovea.cc) now makes it very easy (and free too, for small developer), it's probably the way to go for most.

**Comment by Gerarddus** [comment]
Vacation is very important!

In my current setup, I'm using a (sometimes partly) encrypted billingkey in the billing.xml file and decrypt that using java only. I would like to still be able to use the billing key in the new setup for now. And yes: Minimal security is better than no security at all.

And of course I wholeheartedly agree that serverside validation is the way to go! Will be continued, no doubt. Thanks for all your replies btw!

**Comment by Gerarddus** [comment]
I've tried to adapt your code to make the signature validation myself, but my Java-skills are lacking. Seeing I'm not the only one with this [issue](https://github.com/j3k0/cordova-plugin-purchase/issues/974). Can you reimplement the billing key?

**Comment by hoi4** [comment]
@j3k0 Could you please provide info on how to do on-device signature validation using the billing_key?

**Comment by j3k0** [comment]
Hi @hoi4 - this isn't supported by the plugin anymore. Cf the above thread.

**Comment by hoi4** [comment]
@j3k0 Thanks for the quick reply. Could you provide info on what the server has to do with the purchaseToken from the client in order to get a 200 response from the google API? Somehow the billing key has to be used I assume.

**Comment by j3k0** [comment]
This is not necessary anymore, as it's way better to use the Google Play
Publisher API to validate the purchase (which doesn't use the billing key,
but a google play service account).

I highly recommend you give https://billing.fovea.cc a try, this'll save
you a lot of pain. (the service is operated by my company Fovea)

JC
