### ISSUE TITLE
[IOS] Unable to purchase auto-renewing subscription when user is a member of family sharing

### ISSUE THREAD

**Issue by nvahalik** [j3k0/cordova-plugin-purchase#996]
### System info

iOS: 13.3.1

I'm using Ionic's build system, so I'm not entirely sure about the rest?
Plugin version: 8.1.1

### Expected behavior

Users should be able to sign up for an auto-renewing subscription

### Observed behavior

Users are unable to sign up for an auto-renewing subscription. They are able to load products, but when you call purchase, they get a message "Cannot connect to iTunes store".

    {
        "message": "Cannot connect to iTunes Store", 
        "code": 6777006
    }

### Steps to reproduce

I am unable to reproduce it locally at this point, but I have probably had a dozen people say that they cannot purchase a subscription and this is what ties them all together.

**Comment by Dexus** [comment]
possible that the network is not enabled? I have never gotten this error
message if the network is working and hosts a resolvable.

Am Mo., 24. Feb. 2020 um 18:28 Uhr schrieb Nick Vahalik <
notifications@github.com>:

**Comment by nvahalik** [comment]
I am not sure exactly as this has been a problem that has existed for a long time for us. If this is a network connectivity issue, then that would be something outside of our control.

**Comment by j3k0** [comment]
Thanks for the report. This error (Cannot connect to iTunes store) is triggered by StoreKit.

The "Cannot connect to iTunes Store" issue may be due to one or more of the following reasons:

-    The sandbox may be unreachable. Check the System Status for the status of the iTunes Sandbox.
-    Your app does not have a bundle version (CFBundleVersion). See Setting the Version Number and Build String for more information.
-    Your app is running in the Simulator, which does not support in-app purchase.
-    You are attempting to purchase a product that is unavailable for sale. See Query the App Store for product information before presenting your app’s store UI for more information.

source https://developer.apple.com/library/archive/technotes/tn2413/_index.html#//apple_ref/doc/uid/DTS40016228-CH1-ERROR_MESSAGES-CANNOT_CONNECT_TO_ITUNES_STORE

Is it possible that this happen when kids use the "Ask to Buy" feature?

Plugin has no real support for that, even though it shouldn't create any issues (product just stays in the `INITIATED` state, deferred payment isn't reported though).

https://developer.apple.com/library/archive/technotes/tn2259/_index.html#//apple_ref/doc/uid/DTS40009578-CH1-UPDATE_YOUR_APP_FOR_ASK_TO_BUY

**Comment by j3k0** [comment]
Experimental: https://github.com/j3k0/cordova-plugin-purchase/pull/997

**Comment by nvahalik** [comment]
@j3k0 Thanks for the update. I will attempt to find a way to reproduce this.

**Comment by aesculus** [comment]
Not sure if this is relevant in this situation but I have experienced something similar. A user reported that they could not purchase or validate a purchase because they had suspended purchasing on a family member. This state affected their ability to validate in my app too.

**Comment by nvahalik** [comment]
@aesculus Very interesting.
