### ISSUE TITLE
Is store.update a complete replacement for store.refresh?

### ISSUE THREAD

**Issue by alexcroox** [j3k0/cordova-plugin-purchase#998]
I'm coming back to this plugin since the big 10.x updates since I'm working on a new app.

I notice reading the release notes and documentation that there is a new `store.update` which is a lightweight version of `store.refresh`. 

What is not clear however, is if you even need refresh() anymore? Can it be ignored and use just update() instead? Or is refresh() still 100% required once on load, then update() should be used for subsequent product data updates as it's lighter?

p.s great work on the new documentation, the concepts are _much_ easier to follow now 👏

**Comment by 8bhsolutions** [comment]
@j3k0 
Looking at the code, the update function is currently empty.
Seems like it has not been implemented yet.

**Comment by j3k0** [comment]
It's implemented per platform, only does something on iOS (see
src/js/platforms/ios-adapter.js).

It's not a complete replacement of store.refresh() -- it's a complementary
function you can call when entering the "In-App Purchases" page on your
application (to make sure you have up-to-date product prices and discount
availability).

**TODO**: On android, `store.update()` should probably just call
`store.refresh()` (because google already caches stuff, so store.refresh()
isn't actually such a heavy operation).

**Comment by alexcroox** [comment]
Thanks for the info guys

**Comment by adamduren** [comment]
@j3k0 If you have called `store.refresh` at some point in the past how do you decide in the future whether it is time to call `store.refresh` again, if ever, vs `store.update`

**Comment by j3k0** [comment]
You should call `store.refresh()` again only in response to a user calling a "Restore Purchases" button.

- `.refresh()` might do stuff that require the user to enter store credentials
- `.update()` only light-weight stuff.

That the recommended approach for all platforms.

At the moment, on Android, `refresh()` and `update()` do the same thing, but this might change so better stick to this recommendation.

I agree the naming is quite confusing. It might go over some renaming..
